
const words = [
    { korean: "물", translation: "вода" },
    { korean: "음식", translation: "еда" },
    { korean: "학교", translation: "школа" },
    { korean: "친구", translation: "друг" },
    { korean: "가족", translation: "семья" },
    { korean: "시간", translation: "время" },
    { korean: "일", translation: "работа" },
    { korean: "가다", translation: "идти ( от говорящего)" },
    { korean: "오다", translation: "идти" },
    { korean: "걱정하다", translation: "беспокоиться" },
    { korean: "건강하다", translation: "быть здоровым" },
    { korean: "계란", translation: "яйцо" },
    { korean: "계약", translation: "договор, контракт" },
    { korean: "계약서", translation: "текст договора, контракта" },
    { korean: "고기", translation: "мясо, рыба" },
    { korean: "물", translation: "вода" },
    { korean: "물고기", translation: "рыба" },
    { korean: "고맙다", translation: "быть благодарным" },
    { korean: "고양이", translation: "кошка" },
    { korean: "공부하다", translation: "учить (ся)" },
    { korean: "공원", translation: "парк" },
    { korean: "과자", translation: "кондитерское изделие (конфеты, печенье …)" },
    { korean: "괜찮다", translation: "неплохой, сносный, нормальный" },
    { korean: "교수", translation: "профессор" },
    { korean: "국수", translation: "куксу (корейская лапша)" },
    { korean: "그", translation: "(э) тот" },
    { korean: "그분", translation: "вежл. он, она" },
    { korean: "그녀", translation: "она" },
    { korean: "그래", translation: "да; так; хорошо" },
    { korean: "그러나", translation: "но; однако" },
    { korean: "그릇", translation: "посуда; тарелка" },
    { korean: "그리고", translation: "и; при этом; затем" },
    { korean: "그만", translation: "хватит, достаточно" },
    { korean: "기분", translation: "настроение" },
    { korean: "기쁘다", translation: "радостный, веселый" },
    { korean: "기쁨", translation: "радость" },
    { korean: "길", translation: "дорога" },
    { korean: "길다", translation: "длинный" },
    { korean: "김치", translation: "кимчхи" },
    { korean: "꼭", translation: "обязательно" },
    { korean: "끝", translation: "конец" },
    { korean: "끝나다", translation: "заканчиваться" },
    { korean: "끝내다", translation: "заканчивать, завершать" },
    { korean: "음식", translation: "еда" },
    { korean: "학교", translation: "школа" },
    { korean: "친구", translation: "друг" },
    { korean: "가족", translation: "семья" },
    { korean: "시간", translation: "время" },
    { korean: "일", translation: "работа" },
    { korean: "공부", translation: "учеба" },
    { korean: "여행", translation: "путешествие" },
    { korean: "휴가", translation: "отпуск" },
    { korean: "영화", translation: "фильм" },
    { korean: "음악", translation: "музыка" },
    { korean: "책", translation: "книга" },
    { korean: "커피", translation: "кофе" },
    { korean: "차", translation: "чай" },
    { korean: "빵", translation: "хлеб" },
    { korean: "과일", translation: "фрукты" },
    { korean: "야채", translation: "овощи" },
    { korean: "고기", translation: "мясо" },
    { korean: "생선", translation: "рыба" },
    { korean: "계란", translation: "яйцо" },
    { korean: "우유", translation: "молоко" },
    { korean: "치즈", translation: "сыр" },
    { korean: "버터", translation: "масло" },
    { korean: "소금", translation: "соль" },
    { korean: "설탕", translation: "сахар" },
    { korean: "나", translation: "я" },
    { korean: "나쁘다", translation: "плохой" },
    { korean: "나중에", translation: "потом, в конце" },
    { korean: "날", translation: "день" },
    { korean: "날다", translation: "летать" },
    { korean: "날씨", translation: "погода" },
    { korean: "남자", translation: "мужчина" },
    { korean: "남편", translation: "муж" },
    { korean: "낮", translation: "день" },
    { korean: "내일", translation: "завтра" },
    { korean: "너", translation: "ты" },
    { korean: "놀다", translation: "гулять, веселиться" },
    { korean: "놀음", translation: "игра" },
    { korean: "놈", translation: "презрен. человек, тип" },
    { korean: "농담하다", translation: "шутить" },
    { korean: "누구", translation: "кто" },
    { korean: "뉘", translation: "кто" },
    { korean: "늘", translation: "всегда, постоянно" },
    { korean: "늦다", translation: "поздний; опаздывать" },
    { korean: "달", translation: "луна, месяц" },
    { korean: "닭", translation: "курица" },
    { korean: "당신", translation: "Вы" },
    { korean: "대학", translation: "институт" },
    { korean: "대학교", translation: "университет" },
    { korean: "돈", translation: "деньгим" },
    { korean: "뛰다", translation: "прыгать, подпрыгивать; скакать; бежать" },
    { korean: "라디오", translation: "радио" },
    { korean: "러시아", translation: "Россия" },
    { korean: "러시아말", translation: "русский язык" },
    { korean: "러시아사람", translation: "русский (человек)" },
    { korean: "로봇", translation: "робот" },
    { korean: "마다", translation: "каждый" },
    { korean: "만나다", translation: "встречать (ся)" },
    { korean: "만년필", translation: "авторучка" },
    { korean: "만두", translation: "пельмени" },
    { korean: "만들다", translation: "делать, изготавливать" },
    { korean: "마냑", translation: "если; допустим (предположим), что" },
    { korean: "많다", translation: "многочисленный; много" },
    { korean: "말", translation: "конь; слово; язык" },
    { korean: "말을 걸다", translation: "заводить разговор" },
    { korean: "말하다", translation: "говорить, рассказывать" },
    { korean: "매우", translation: "очень" },
    { korean: "매일", translation: "каждый день" },
    { korean: "머리", translation: "голова" },
    { korean: "머리가 나쁘다", translation: "глупый" },
    { korean: "머리가 좋다", translation: "умный" },
    { korean: "모르다", translation: "не знать; не уметь" },
    { korean: "무엇", translation: "что; что – то" },
    { korean: "무엇인가", translation: "что – нибудь" },
    { korean: "미", translation: "красота" },
    { korean: "미국", translation: "Америка" },
    { korean: "미소", translation: "улыбка" },
    { korean: "미소를 짓다", translation: "улыбаться" },
    { korean: "거짓말", translation: " ложь" },
    { korean: "건강", translation: "здоровье " },
    { korean: "급료", translation: "зарплата" },
    { korean: "기억", translation: "память" },
    { korean: "깊다", translation: "глубокий " },
    { korean: "대통령", translation: "президент" },
    { korean: "맥락", translation: "контекст" },
    { korean: "박람회", translation: "ярмарка" },
    { korean: "박물관", translation: "музей" },
    { korean: "속력", translation: "скорость" },
    { korean: "속도", translation: "скорость" },
    { korean: "식당", translation: "ресторан " },
    { korean: "식물", translation: "растение" },
    { korean: "심리학", translation: "психология" },
    { korean: "일본", translation: "Япония" },
    { korean: "읽다", translation: "читать" },
    { korean: "점심", translation: "обед" },
    { korean: "정류장", translation: "остановка" },
    { korean: "진리", translation: "правда" },
    { korean: "칼", translation: "нож" },
    { korean: "학년", translation: "учебный год" },
    { korean: "가을", translation: "осень" },
    { korean: "겨울", translation: "зима" },
    { korean: "교실", translation: "класс" },
    { korean: "금요일", translation: "пятница" },
    { korean: "낮", translation: "день" },
    { korean: "날", translation: "день" },
    { korean: "내일", translation: "завтра" },
    { korean: "년", translation: "год" },
    { korean: "다음", translation: "следующий" },
    { korean: "달", translation: "месяц (корейское слово)" },
    { korean: "월", translation: "месяц (китайское слово)" },
    { korean: "달러", translation: "доллар" },
    { korean: "동안", translation: "в течение" },
    { korean: "마다", translation: "каждый" },
    { korean: "몇", translation: "сколько" },
    { korean: "얼마나", translation: "сколько" },
    { korean: "목요일", translation: "четверг" },
    { korean: "밤", translation: "ночь" },
    { korean: "봄", translation: "весна" },
    { korean: "분", translation: "минута" },
    { korean: "사람", translation: "человек" },
    { korean: "среда", translation: "среда" },
    { korean: "시", translation: "час" },
    { korean: "시간", translation: "час (промежуток времени)" },
    { korean: "아침", translation: "утро" },
    { korean: "어제", translation: "вчера" },
    { korean: "여름", translation: "лето" },
    { korean: "연필", translation: "карандаш" },
    { korean: "오늘", translation: "сегодня" },
    { korean: "오전", translation: "первая половина дня" },
    { korean: "오후", translation: "вторая половина дня" },
    { korean: "요일", translation: "день недели" },
    { korean: "월요일", translation: "понедельник" },
    { korean: "일요일", translation: "воскресенье" },
    { korean: "자정", translation: "полночь" },
    { korean: "저녁", translation: "вечер" },
    { korean: "전화", translation: "телефон" },
    { korean: "지난", translation: "прошлый" },
    { korean: "지난 번에", translation: "прошлый раз" },
    { korean: "초", translation: "секунда" },
    { korean: "토요일", translation: "суббота" },
    { korean: "학생", translation: "ученик, студент" },
    { korean: "화요일", translation: "вторник" },
    { korean: "안녕하세요", translation: "здравствуйте" },  
{ korean: "감사합니다", translation: "спасибо" },  
{ korean: "사랑해", translation: "я тебя люблю" },  
{ korean: "고양이", translation: "кошка" },  
{ korean: "강아지", translation: "собака" },  
{ korean: "커피", translation: "кофе" },  
{ korean: "물", translation: "вода" },  
{ korean: "학교", translation: "школа" },  
{ korean: "선생님", translation: "учитель" },  
{ korean: "먹다", translation: "есть" },  
{ korean: "보다", translation: "смотреть" },  
{ korean: "하다", translation: "делать" },  
{ korean: "있다", translation: "иметься, существовать" },  
{ korean: "없다", translation: "отсутствовать" },  
{ korean: "좋다", translation: "хороший" },  
{ korean: "나쁘다", translation: "плохой" },  
{ korean: "크다", translation: "большой" },  
{ korean: "작다", translation: "маленький" },  
{ korean: "맛있다", translation: "вкусный" },  
{ korean: "맛없다", translation: "невкусный" },  
{ korean: "비싸다", translation: "дорогой" },  
{ korean: "싸다", translation: "дешевый" },  
{ korean: "빠르다", translation: "быстрый" },  
{ korean: "느리다", translation: "медленный" },  
{ korean: "예쁘다", translation: "красивый" },  
{ korean: "똑똑하다", translation: "умный" },  
{ korean: "행복하다", translation: "счастливый" },  
{ korean: "슬프다", translation: "грустный" },  
{ korean: "덥다", translation: "жарко" },  
{ korean: "춥다", translation: "холодно" },  
{ korean: "배고프다", translation: "голодный" },  
{ korean: "목마르다", translation: "хотеть пить" },  
{ korean: "피곤하다", translation: "усталый" },  
{ korean: "아프다", translation: "больной" },  
{ korean: "건강하다", translation: "здоровый" },  
{ korean: "재미있다", translation: "интересный, веселый" },  
{ korean: "재미없다", translation: "скучный" },  
{ korean: "어렵다", translation: "трудный" },  
{ korean: "쉽다", translation: "легкий" },  
{ korean: "많다", translation: "много" },  
{ korean: "적다", translation: "мало" },  
{ korean: "같다", translation: "такой же" },  
{ korean: "다르다", translation: "другой" },  
{ korean: "옳다", translation: "правильный" },  
{ korean: "그릇되다", translation: "неправильный" },  
{ korean: "필요하다", translation: "нужный" },  
{ korean: "불필요하다", translation: "ненужный" },  
{ korean: "가능하다", translation: "возможный" },  
{ korean: "불가능하다", translation: "невозможный" },  
{ korean: "중요하다", translation: "важный" },  
{ korean: "시작하다", translation: "начинать" },  
{ korean: "끝나다", translation: "заканчивать" },  
{ korean: "열다", translation: "открывать" },  
{ korean: "닫다", translation: "закрывать" },  
{ korean: "들어오다", translation: "входить" },  
{ korean: "나가다", translation: "выходить" },  
{ korean: "앉다", translation: "сидеть" },  
{ korean: "일어나다", translation: "вставать" },  
{ korean: "자다", translation: "спать" },  
{ korean: "깨다", translation: "просыпаться" },  
{ korean: "웃다", translation: "смеяться" },  
{ korean: "울다", translation: "плакать" },  
{ korean: "말하다", translation: "говорить" },  
{ korean: "듣다", translation: "слушать" },  
{ korean: "읽다", translation: "читать" },  
{ korean: "쓰다", translation: "писать" },  
{ korean: "생각하다", translation: "думать" },  
{ korean: "알다", translation: "знать" },  
{ korean: "모르다", translation: "не знать" },  
{ korean: "기억하다", translation: "помнить" },  
{ korean: "잊다", translation: "забывать" },  
{ korean: "원하다", translation: "хотеть" },  
{ korean: "좋아하다", translation: "нравиться" },  
{ korean: "싫어하다", translation: "не нравиться" },  
{ korean: "도와주다", translation: "помогать" },  
{ korean: "기다리다", translation: "ждать" },  
{ korean: "만나다", translation: "встречать" },  
{ korean: "헤어지다", translation: "расставаться" },  
{ korean: "사다", translation: "покупать" },  
{ korean: "팔다", translation: "продавать" },  
{ korean: "주다", translation: "давать" },  
{ korean: "받다", translation: "получать" },  
{ korean: "가지다", translation: "иметь" },  
{ korean: "버리다", translation: "выбрасывать" },  
{ korean: "찾다", translation: "искать" },  
{ korean: "발견하다", translation: "находить" },  
{ korean: "잃다", translation: "терять" },  
{ korean: "데려오다", translation: "приносить" },  
{ korean: "데려가다", translation: "уносить" },  
{ korean: "보내다", translation: "отправлять" },  
{ korean: "도착하다", translation: "прибывать" },  
{ korean: "출발하다", translation: "отправляться" },  
{ korean: "이사하다", translation: "переезжать" },  
{ korean: "살다", translation: "жить" },  
{ korean: "죽다", translation: "умирать" },  
{ korean: "태어나다", translation: "рождаться" },  
{ korean: "자라다", translation: "расти" },  
{ korean: "변하다", translation: "меняться" },  
{ korean: "공부하다", translation: "учиться" },  
{ korean: "가르치다", translation: "учить (кого-то)" },  
{ korean: "일하다", translation: "работать" },  
{ korean: "쉬다", translation: "отдыхать" },  
{ korean: "놀다", translation: "играть" },  
{ korean: "운동하다", translation: "заниматься спортом" },  
{ korean: "걷다", translation: "гулять" },  
{ korean: "뛰다", translation: "бежать" },  
{ korean: "춤추다", translation: "танцевать" },  
{ korean: "노래하다", translation: "петь" },  
{ korean: "연주하다", translation: "играть (на инструменте)" },  
{ korean: "그리다", translation: "рисовать" },  
{ korean: "만들다", translation: "делать, создавать" },  
{ korean: "고치다", translation: "чинить" },  
{ korean: "깨끗하다", translation: "чистый" },  
{ korean: "더럽다", translation: "грязный" },  
{ korean: "씻다", translation: "мыть" },  
{ korean: "닦다", translation: "вытирать" },  
{ korean: "치우다", translation: "убирать" },  
{ korean: "요리하다", translation: "готовить (еду)" },  
{ korean: "마시다", translation: "пить" },  
{ korean: "씹다", translation: "жевать" },  
{ korean: "삼키다", translation: "глотать" },  
{ korean: "배부르다", translation: "быть сытым" },  
{ korean: "입다", translation: "надевать (одежду)" },  
{ korean: "벗다", translation: "снимать (одежду)" },  
{ korean: "신다", translation: "надевать (обувь)" },  
{ korean: "벗기다", translation: "снимать (обувь)" },  
{ korean: "빗다", translation: "расчесывать" },  
{ korean: "자르다", translation: "стричь, резать" },  
{ korean: "태우다", translation: "жечь" },  
{ korean: "끓이다", translation: "кипятить" },  
{ korean: "얼다", translation: "замерзать" },  
{ korean: "녹다", translation: "таять" },  
{ korean: "젖다", translation: "мокнуть" },  
{ korean: "말리다", translation: "сушить" },  
{ korean: "불다", translation: "дуть" },  
{ korean: "비가 오다", translation: "идет дождь" },  
{ korean: "눈이 오다", translation: "идет снег" },  
{ korean: "번개가 치다", translation: "сверкает молния" },  
{ korean: "천둥이 치다", translation: "гремит гром" },  
{ korean: "바람이 불다", translation: "дует ветер" },  
{ korean: "해가 뜨다", translation: "восходит солнце" },  
{ korean: "해가 지다", translation: "заходит солнце" },  
{ korean: "달이 뜨다", translation: "восходит луна" },  
{ korean: "별이 빛나다", translation: "светят звезды" },  
{ korean: "구름이 끼다", translation: "облачно" },  
{ korean: "안개가 끼다", translation: "туманно" },  
{ korean: "무지개가 뜨다", translation: "появляется радуга" },  
{ korean: "봄", translation: "весна" },  
{ korean: "여름", translation: "лето" },  
{ korean: "가을", translation: "осень" },  
{ korean: "겨울", translation: "зима" },  
{ korean: "아침", translation: "утро" },  
{ korean: "점심", translation: "день" },  
{ korean: "저녁", translation: "вечер" },  
{ korean: "밤", translation: "ночь" },  
{ korean: "오늘", translation: "сегодня" },  
{ korean: "어제", translation: "вчера" },  
{ korean: "내일", translation: "завтра" },  
{ korean: "모레", translation: "послезавтра" },  
{ korean: "글피", translation: "через два дня" },  
{ korean: "지난주", translation: "на прошлой неделе" },  
{ korean: "이번주", translation: "на этой неделе" },  
{ korean: "다음주", translation: "на следующей неделе" },  
{ korean: "지난달", translation: "в прошлом месяце" },  
{ korean: "이번달", translation: "в этом месяце" },  
{ korean: "다음달", translation: "в следующем месяце" },  
{ korean: "작년", translation: "в прошлом году" },  
{ korean: "올해", translation: "в этом году" },  
{ korean: "내년", translation: "в следующем году" },  
{ korean: "후년", translation: "через год" },  
{ korean: "요전년", translation: "год назад" },  
{ korean: "요즘", translation: "в последнее время" },  
{ korean: "최근", translation: "недавно" },  
{ korean: "옛날", translation: "давно" },  
{ korean: "지금", translation: "сейчас" },  
{ korean: "이제", translation: "теперь" },  
{ korean: "곧", translation: "скоро" },  
{ korean: "나중에", translation: "позже" },  
{ korean: "언제", translation: "когда" },  
{ korean: "어디", translation: "где" },  
{ korean: "누구", translation: "кто" },  
{ korean: "무엇", translation: "что" },  
{ korean: "어떻게", translation: "как" },  
{ korean: "왜", translation: "почему" },  
{ korean: "얼마", translation: "сколько" },  
{ korean: "몇", translation: "сколько (в вопросах)" },  
{ korean: "어느", translation: "какой" },  
{ korean: "무슨", translation: "какой (какого рода)" },  
{ korean: "어떤", translation: "какой (какого вида)" },  
{ korean: "모든", translation: "все" },  
{ korean: "전부", translation: "все (целиком)" },  
{ korean: "다", translation: "все (без исключения)" },  
{ korean: "아무", translation: "любой" },  
{ korean: "각", translation: "каждый" },  
{ korean: "많은", translation: "много (чего-то)" },  
{ korean: "적은", translation: "мало (чего-то)" },  
{ korean: "조금", translation: "немного" },  
{ korean: "약간", translation: "немного (чуть-чуть)" },  
{ korean: "많이", translation: "много (по количеству)" },  
{ korean: "적게", translation: "мало (по количеству)" },  
{ korean: "전혀", translation: "совсем не" },  
{ korean: "절대", translation: "никогда (в отрицаниях)" },  
{ korean: "별로", translation: "не очень" },  
{ korean: "거의", translation: "почти" },  
{ korean: "대부분", translation: "большая часть" },  
{ korean: "일부", translation: "часть" },  
{ korean: "반", translation: "половина" },  
{ korean: "전체", translation: "целое" },  
{ korean: "개인", translation: "личность" },  
{ korean: "사람", translation: "человек" },  
{ korean: "남자", translation: "мужчина" },  
{ korean: "여자", translation: "женщина" },  
{ korean: "아이", translation: "ребенок" },  
{ korean: "어른", translation: "взрослый" },  
{ korean: "노인", translation: "пожилой человек" },  
{ korean: "청년", translation: "молодой человек" },  
{ korean: "소년", translation: "мальчик" },  
{ korean: "소녀", translation: "девочка" },  
{ korean: "아기", translation: "младенец" },  
{ korean: "부모", translation: "родители" },  
{ korean: "아버지", translation: "отец" },  
{ korean: "어머니", translation: "мать" },  
{ korean: "아들", translation: "сын" },  
{ korean: "딸", translation: "дочь" },  
{ korean: "형", translation: "старший брат (для мужчин)" },  
{ korean: "누나", translation: "старшая сестра (для мужчин)" },  
{ korean: "오빠", translation: "старший брат (для женщин)" },  
{ korean: "언니", translation: "старшая сестра (для женщин)" },  
{ korean: "동생", translation: "младший брат/сестра" },  
{ korean: "남편", translation: "муж" },  
{ korean: "아내", translation: "жена" },  
{ korean: "할아버지", translation: "дедушка" },  
{ korean: "할머니", translation: "бабушка" },  
{ korean: "손자", translation: "внук" },  
{ korean: "손녀", translation: "внучка" },  
{ korean: "삼촌", translation: "дядя" },  
{ korean: "이모", translation: "тетя" },  
{ korean: "조카", translation: "племянник/племянница" },  
{ korean: "사촌", translation: "двоюродный брат/сестра" },  
{ korean: "친척", translation: "родственник" },  
{ korean: "가족", translation: "семья" },  
{ korean: "집", translation: "дом" },  
{ korean: "방", translation: "комната" },  
{ korean: "거실", translation: "гостиная" },  
{ korean: "주방", translation: "кухня" },  
{ korean: "화장실", translation: "туалет" },  
{ korean: "욕실", translation: "ванная" },  
{ korean: "침실", translation: "спальня" },  
{ korean: "서재", translation: "кабинет" },  
{ korean: "다락방", translation: "чердак" },  
{ korean: "지하실", translation: "подвал" },  
{ korean: "마당", translation: "двор" },  
{ korean: "정원", translation: "сад" },  
{ korean: "담장", translation: "забор" },  
{ korean: "문", translation: "дверь" },  
{ korean: "창문", translation: "окно" },  
{ korean: "벽", translation: "стена" },  
{ korean: "천장", translation: "потолок" },  
{ korean: "바닥", translation: "пол" },  
{ korean: "계단", translation: "лестница" },  
{ korean: "지붕", translation: "крыша" },  
{ korean: "굴뚝", translation: "дымоход" },  
{ korean: "현관", translation: "вход" },  
{ korean: "복도", translation: "коридор" },  
{ korean: "베란다", translation: "балкон" },  
{ korean: "발코니", translation: "балкон" },  
{ korean: "옥상", translation: "крыша (здания)" },  
{ korean: "건물", translation: "здание" },  
{ korean: "아파트", translation: "квартира" },  
{ korean: "빌라", translation: "вилла" },  
{ korean: "주택", translation: "дом (отдельный)" },  
{ korean: "연립주택", translation: "таунхаус" },  
{ korean: "오피스텔", translation: "офис-квартира" },  
{ korean: "기숙사", translation: "общежитие" },  
{ korean: "호텔", translation: "отель" },  
{ korean: "모텔", translation: "мотель" },  
{ korean: "펜션", translation: "гостевой дом" },  
{ korean: "리조트", translation: "курорт" },  
{ korean: "콘도", translation: "кондоминиум" },  
{ korean: "숙소", translation: "жилье" },  
{ korean: "숙박시설", translation: "место проживания" },  
{ korean: "학교", translation: "школа" },  
{ korean: "대학교", translation: "университет" },  
{ korean: "도서관", translation: "библиотека" },  
{ korean: "박물관", translation: "музей" },  
{ korean: "미술관", translation: "художественный галерея" },  
{ korean: "영화관", translation: "кинотеатр" },  
{ korean: "극장", translation: "театр" },  
{ korean: "콘서트홀", translation: "концертный зал" },  
{ korean: "스타디움", translation: "стадион" },  
{ korean: "체육관", translation: "спортзал" },  
{ korean: "수영장", translation: "бассейн" },  
{ korean: "공원", translation: "парк" },  
{ korean: "동물원", translation: "зоопарк" },  
{ korean: "식물원", translation: "ботанический сад" },  
{ korean: "놀이공원", translation: "парк развлечений" },  
{ korean: "유원지", translation: "место отдыха" },  
{ korean: "쇼핑몰", translation: "торговый центр" },  
{ korean: "백화점", translation: "универмаг" },  
{ korean: "슈퍼마켓", translation: "супермаркет" },  
{ korean: "편의점", translation: "круглосуточный магазин" },  
{ korean: "시장", translation: "рынок" },  
{ korean: "가게", translation: "магазин" },  
{ korean: "식당", translation: "ресторан" },  
{ korean: "카페", translation: "кафе" },  
{ korean: "패스트푸드점", translation: "фастфуд" },  
{ korean: "주점", translation: "бар" },  
{ korean: "호프", translation: "пивной бар" },  
{ korean: "찻집", translation: "чайная" },  
{ korean: "병원", translation: "больница" },  
{ korean: "약국", translation: "аптека" },  
{ korean: "경찰서", translation: "полицейский участок" },  
{ korean: "소방서", translation: "пожарная станция" },  
{ korean: "우체국", translation: "почта" },  
{ korean: "은행", translation: "банк" },  
{ korean: "증권사", translation: "брокерская фирма" },  
{ korean: "보험사", translation: "страховая компания" },  
{ korean: "여행사", translation: "турагентство" },  
{ korean: "항공사", translation: "авиакомпания" },  
{ korean: "철도역", translation: "железнодорожная станция" },  
{ korean: "버스터미널", translation: "автовокзал" },  
{ korean: "공항", translation: "аэропорт" },  
{ korean: "항구", translation: "порт" },  
{ korean: "주차장", translation: "парковка" },  
{ korean: "정류장", translation: "остановка" },  
{ korean: "지하철역", translation: "станция метро" },  
{ korean: "사거리", translation: "перекресток" },  
{ korean: "신호등", translation: "светофор" },  
{ korean: "육교", translation: "пешеходный мост" },  
{ korean: "지하도", translation: "подземный переход" },  
{ korean: "길", translation: "дорога" },  
{ korean: "도로", translation: "автомагистраль" },  
{ korean: "고속도로", translation: "шоссе" },  
{ korean: "골목", translation: "переулок" },  
{ korean: "다리", translation: "мост" },  
{ korean: "터널", translation: "туннель" },  
{ korean: "강", translation: "река" },  
{ korean: "호수", translation: "озеро" },  
{ korean: "바다", translation: "море" },  
{ korean: "산", translation: "гора" },  
{ korean: "숲", translation: "лес" },  
{ korean: "들", translation: "поле" },  
{ korean: "사막", translation: "пустыня" },  
{ korean: "계곡", translation: "долина" },  
{ korean: "폭포", translation: "водопад" },  
{ korean: "동굴", translation: "пещера" },  
{ korean: "섬", translation: "остров" },  
{ korean: "반도", translation: "полуостров" },  
{ korean: "대륙", translation: "континент" },  
{ korean: "지구", translation: "Земля" },  
{ korean: "달", translation: "Луна" },  
{ korean: "태양", translation: "Солнце" },  
{ korean: "별", translation: "звезда" },  
{ korean: "은하", translation: "галактика" },  
{ korean: "우주", translation: "космос" },  
{ korean: "하늘", translation: "небо" },  
{ korean: "구름", translation: "облако" },  
{ korean: "비", translation: "дождь" },  
{ korean: "눈", translation: "снег" },  
{ korean: "우박", translation: "град" },  
{ korean: "안개", translation: "туман" },  
{ korean: "바람", translation: "ветер" },  
{ korean: "번개", translation: "молния" },  
{ korean: "천둥", translation: "гром" },  
{ korean: "무지개", translation: "радуга" },  
{ korean: "이슬", translation: "роса" },  
{ korean: "서리", translation: "иней" },  
{ korean: "얼음", translation: "лед" },  
{ korean: "증기", translation: "пар" },  
{ korean: "불", translation: "огонь" },  
{ korean: "불고기", translation: "корейское жаркое" },  
{ korean: "김치", translation: "кимчи" },  
{ korean: "학생", translation: "студент" },  
{ korean: "한국", translation: "Корея" },  
{ korean: "미국", translation: "Америка" },  
{ korean: "일본", translation: "Япония" },  
{ korean: "중국", translation: "Китай" },  
{ korean: "차", translation: "чай" },  
{ korean: "빵", translation: "хлеб" },  
{ korean: "사과", translation: "яблоко" },  
{ korean: "바나나", translation: "банан" },  
{ korean: "우유", translation: "молоко" },  
{ korean: "친구", translation: "друг" },  
{ korean: "이름", translation: "имя" },  
{ korean: "나이", translation: "возраст" },  
{ korean: "생일", translation: "день рождения" },  
{ korean: "시간", translation: "время" },  
{ korean: "여기", translation: "здесь" },  
{ korean: "거기", translation: "там" },  
{ korean: "저기", translation: "вон там" },  
{ korean: "뭐", translation: "что" },  
{ korean: "예", translation: "да" },  
{ korean: "아니요", translation: "нет" },  
{ korean: "좋아요", translation: "хорошо" },  
{ korean: "싫어요", translation: "не нравится" },  
{ korean: "맛있어요", translation: "вкусно" },  
{ korean: "배고파요", translation: "я голоден" },  
{ korean: "목말라요", translation: "я хочу пить" },  
{ korean: "피곤해요", translation: "я устал" },  
{ korean: "졸려요", translation: "я хочу спать" },  
{ korean: "기뻐요", translation: "я рад" },  
{ korean: "슬퍼요", translation: "мне грустно" },  
{ korean: "화가 나요", translation: "я злюсь" },  
{ korean: "걱정돼요", translation: "я волнуюсь" },  
{ korean: "미안해요", translation: "извините" },  
{ korean: "괜찮아요", translation: "все в порядке" },  
{ korean: "실례합니다", translation: "простите (за беспокойство)" },  
{ korean: "처음 뵙겠습니다", translation: "приятно познакомиться" },  
{ korean: "잘 부탁드립니다", translation: "буду признателен за вашу помощь" },  
{ korean: "잘 지냈어요?", translation: "как дела?" },  
{ korean: "네, 잘 지냈어요", translation: "да, все хорошо" },  
{ korean: "아니요, 잘 못 지냈어요", translation: "нет, не очень" },  
{ korean: "몇 시예요?", translation: "который час?" },  
{ korean: "얼마예요?", translation: "сколько это стоит?" },  
{ korean: "도와주세요", translation: "помогите мне" },  
{ korean: "알겠습니다", translation: "я понял" },  
{ korean: "모르겠습니다", translation: "я не знаю" },  
{ korean: "다시 말씀해 주세요", translation: "повторите, пожалуйста" },  
{ korean: "천천히 말씀해 주세요", translation: "говорите медленнее, пожалуйста" },  
{ korean: "영어 할 줄 아세요?", translation: "вы говорите по-английски?" },  
{ korean: "러시아어 할 줄 아세요?", translation: "вы говорите по-русски?" },  
{ korean: "한국어 잘 못해요", translation: "я плохо говорю по-корейски" },  
{ korean: "조금 할 줄 알아요", translation: "я знаю немного" },  
{ korean: "이거 주세요", translation: "дайте мне это, пожалуйста" },  
{ korean: "저거 주세요", translation: "дайте мне то, пожалуйста" },  
{ korean: "추천해 주세요", translation: "посоветуйте мне, пожалуйста" },  
{ korean: "맛있겠다", translation: "выглядит вкусно" },  
{ korean: "건배", translation: "ваше здоровье! (тост)" },  
{ korean: "생일 축하합니다", translation: "с днем рождения" },  
{ korean: "새해 복 많이 받으세요", translation: "с Новым годом" },  
{ korean: "메리 크리스마스", translation: "с Рождеством" },  
{ korean: "축하합니다", translation: "поздравляю" },  
{ korean: "행운을 빌어요", translation: "удачи" },  
{ korean: "힘내세요", translation: "держитесь" },  
{ korean: "잘했어요", translation: "ты хорошо справился" },  
{ korean: "사진 찍어 주세요", translation: "сфотографируйте меня, пожалуйста" },  
{ korean: "여기서 사진 찍어도 돼요?", translation: "можно здесь фотографировать?" },  
{ korean: "예쁘다", translation: "красиво" },  
{ korean: "멋있다", translation: "круто" },  
{ korean: "귀엽다", translation: "милый" },
];

let currentIndex = 0;

// Функция для получения случайного индекса
function getRandomIndex() {
    return Math.floor(Math.random() * words.length);
}

// Функция для обновления слова
function updateWord() {
    const word = words[currentIndex];
    document.getElementById("korean-word").textContent = word.korean;
    document.getElementById("translation-box").textContent = word.translation;
}

// Функция для перехода к следующему слову (случайно)
function nextWord() {
    currentIndex = getRandomIndex();
    updateWord();
    speakText(words[currentIndex].korean);
}

// Функция для перехода к предыдущему слову (случайно)
function previousWord() {
    currentIndex = getRandomIndex();
    updateWord();
    speakText(words[currentIndex].korean);
}

// Функция для озвучивания текста
function speakText(text) {
    if (text) {
        const utterance = new SpeechSynthesisUtterance(text);
        utterance.lang = 'ko-KR'; // Для корейского языка
        speechSynthesis.speak(utterance);
    }
}

// Функция для воспроизведения аудио
function playAudio() {
    speakText(words[currentIndex].korean);
}

// Инициализация первого слова
updateWord();
