
const words = [
      { korean: "가게", translation: "магазин, лавка" },
    { korean: "가구", translation: "мебель" },
    { korean: "가까이", translation: "близко, рядом, около" },
    { korean: "가깝다", translation: "близкий" },
    { korean: "가끔", translation: "иногда, время от времени" },
    { korean: "가난", translation: "бедность, нищета" },
    { korean: "가난하다", translation: "бедный, нищий" },
    { korean: "가늘다", translation: "тонкий" },
    { korean: "가다", translation: "идти (от говорящего)" },
    { korean: "가득", translation: "полностью" },
    { korean: "가득하다", translation: "быть полным (заполненным, забитым) до отказа" },
    { korean: "가지", translation: "ветка; сорт, вид" },
    { korean: "가지다", translation: "брать, иметь (при себе)" },
    { korean: "가격", translation: "цена, стоимость" },
    { korean: "가깝다", translation: "крутой (о горах)" },
    { korean: "각각", translation: "каждый; разнообразный" },
    { korean: "각오", translation: "осознание; приготовление" },
    { korean: "간격", translation: "промежуток, интервал" },
    { korean: "간절하다", translation: "сердечный, искренний; горячий (о желании)" },
    { korean: "갈비", translation: "ребра" },
    { korean: "갈아입다", translation: "переодевать(ся)" },
    { korean: "갈아타다", translation: "пересаживаться" },
    { korean: "감동", translation: "(глубокое) впечатление, чувство; волнение" },
    { korean: "감기", translation: "простуда" },
    { korean: "감기약", translation: "лекарство от простуды" },
    { korean: "감다", translation: "мыться; купаться" },
    { korean: "감동", translation: "(глубокое) впечатление, чувство" },
    { korean: "감동하다", translation: "быть глубоко тронутым" },
    { korean: "감정", translation: "чувство" },
    { korean: "감탄", translation: "восхищение" },
    { korean: "감히", translation: "сметь, осмелиться" },
    { korean: "갑자기", translation: "внезапно, вдруг" },
    { korean: "값", translation: "цена" },
    { korean: "값비싸다", translation: "дорогой" },
    { korean: "갓", translation: "только что; корейская шляпа" },
    { korean: "강", translation: "река" },
    { korean: "강가", translation: "берег реки" },
    { korean: "강물", translation: "поток в реке" },
    { korean: "강도", translation: "бандит, разбойник" },
    { korean: "개", translation: "собака" },
    { korean: "개발", translation: "разработка" },
    { korean: "개발하다", translation: "разрабатывать" },
    { korean: "개울", translation: "ручей" },
    { korean: "개이다", translation: "проясняться (о небе)" },
    { korean: "개혁", translation: "реформа, преобразование" },
    { korean: "거느리다", translation: "вести за собой" },
    { korean: "거두다", translation: "собирать, убирать" },
    { korean: "거리", translation: "расстояние; улица" },
    { korean: "거리바닥", translation: "асфальт, полотно дороги" },
    { korean: "거의", translation: "почти, едва" },
    { korean: "거짓", translation: "ложный, фальшивый" },
    { korean: "거짓말", translation: "ложь" },
    { korean: "거짓말쟁이", translation: "лжец, врун" },
    { korean: "걱정", translation: "беспокойство" },
    { korean: "걱정하다", translation: "беспокоиться" },
    { korean: "건강", translation: "здоровье" },
    { korean: "건강하다", translation: "быть здоровым" },
    { korean: "건너가다", translation: "переходить" },
    { korean: "건너편", translation: "противоположная сторона" },
    { korean: "건립하다", translation: "воздвигать, создавать (организацию)" },
    { korean: "건물", translation: "здание, строение" },
    { korean: "건설", translation: "строительство" },
    { korean: "건설하다", translation: "строить" },
    { korean: "건축", translation: "стройка" },
    { korean: "건축가", translation: "строитель" },
    { korean: "건축하다", translation: "строить, возводить" },
    { korean: "걷다", translation: "ходить пешком" },
    { korean: "걸다", translation: "вешать" },
    { korean: "걸리다", translation: "висеть, быть повешенным; занимать (о времени)" },
    { korean: "걸상", translation: "стул, скамья" },
    { korean: "걸음", translation: "шаг" },
    { korean: "검사", translation: "проверка, осмотр, контроль" },
    { korean: "것", translation: "вещь; имя" },
    { korean: "겉", translation: "внешняя сторона (чего-л.)" },
    { korean: "게으르다", translation: "ленивый" },
    { korean: "게을러하다", translation: "лениться" },
    { korean: "겨누다", translation: "целиться" },
    { korean: "겨우", translation: "с трудом, едва, еле" },
    { korean: "겨울", translation: "зима" },
    { korean: "견디다", translation: "терпеть, выдерживать" },
    { korean: "견학", translation: "экскурсия, осмотр" },
    { korean: "결과", translation: "результат" },
    { korean: "결국", translation: "в конце концов" },
    { korean: "결석하다", translation: "отсутствовать (на занятиях)" },
    { korean: "결심하다", translation: "решить(ся)" },
    { korean: "결정", translation: "решение" },
    { korean: "결정하다", translation: "решать" },
    { korean: "결혼", translation: "женитьба, брак" },
    { korean: "결혼식", translation: "свадьба, церемония бракосочетания" },
    { korean: "겸", translation: "примерно, около" },
    { korean: "경고문", translation: "предупреждение (текст)" },
    { korean: "경기", translation: "соревнование" },
    { korean: "경기장", translation: "стадион, спортплощадка" },
    { korean: "경배", translation: "честь" },
    { korean: "경비", translation: "расходы, издержки" },
    { korean: "경우", translation: "случай, ситуация" },
    { korean: "경쟁", translation: "конкуренция" },
    { korean: "경쟁하다", translation: "конкурировать" },
    { korean: "경제", translation: "экономика" },
    { korean: "경찰", translation: "полиция" },
    { korean: "경치", translation: "природа, пейзаж" },
    { korean: "경향", translation: "тенденция" },
    { korean: "경험", translation: "опыт" },
    { korean: "곁", translation: "рядом, сбоку" },
    { korean: "계란", translation: "яйцо" },
    { korean: "계속", translation: "продолжение" },
    { korean: "계속하다", translation: "продолжать(ся)" },
    { korean: "계시다", translation: "века, быть, находиться" },
    { korean: "계약", translation: "договор, контракт" },
    { korean: "계약서", translation: "текст договора (контракта)" },
    { korean: "계획", translation: "план" },
    { korean: "고개", translation: "голова; перевал" },
    { korean: "고기", translation: "мясо, рыба" },
    { korean: "고기잡이", translation: "рыбалка" },
    { korean: "고르다", translation: "выбирать; ровный" },
    { korean: "고맙다", translation: "быть благодарным" },
    { korean: "고마운", translation: "благодарность" },
    { korean: "고민", translation: "мука, страдание" },
    { korean: "고분", translation: "могильный курган" },
    { korean: "고생", translation: "невзгода, лишение" },
    { korean: "고생하다", translation: "страдать" },
    { korean: "고속", translation: "большая скорость" },
    { korean: "고속도로", translation: "скоростное шоссе; высокие темпы" },
    { korean: "고아원", translation: "интернат, детдом, приют" },
    { korean: "고양이", translation: "кошка" },
    { korean: "고장", translation: "поломка, неисправность" },
    { korean: "고장나다", translation: "выйти из строя, сломаться" },
    { korean: "군", translation: "уезд" },
    { korean: "군대", translation: "армия" },
    { korean: "굳다", translation: "твердый, прочный" },
    { korean: "굴", translation: "пещера, нора" },
    { korean: "굵다", translation: "толстый" },
    { korean: "굶다", translation: "голодать" },
    { korean: "굽다", translation: "сгибать; жарить" },
    { korean: "궁궐", translation: "дворец" },
    { korean: "궁금하다", translation: "тревожиться, беспокоиться" },
    { korean: "권투", translation: "бокс" },
    { korean: "권투선수", translation: "боксер" },
    { korean: "권하다", translation: "предлагать" },
    { korean: "귀국", translation: "возвращение на родину" },
    { korean: "귀엽다", translation: "милый, симпатичный" },
    { korean: "귀중하다", translation: "дорогой, благородный" },
    { korean: "규모", translation: "масштаб, размер" },
    { korean: "규율", translation: "порядок, дисциплина" },
    { korean: "규칙", translation: "правило" },
    { korean: "규칙적", translation: "регулярный, правильный" },
    { korean: "귤", translation: "цитрусовые (мандарин, апельсин)" },
    { korean: "그", translation: "(э)тот" },
    { korean: "그분", translation: "вежл. он, она" },
    { korean: "그것", translation: "(э)то; он, она, оно" },
    { korean: "그냥", translation: "в таком виде (так), как есть; как и раньше, по-прежнему; просто; как ни в чем не бывало" },
    { korean: "그녀", translation: "она" },
    { korean: "그늘", translation: "тень" },
    { korean: "그대로", translation: "так; в таком виде" },
    { korean: "그래", translation: "да; так; хорошо" },
    { korean: "그래도", translation: "но; однако" },
    { korean: "그래서", translation: "поэтому" },
    { korean: "그러나", translation: "но; однако" },
    { korean: "그러다", translation: "делать так" },
    { korean: "그러면", translation: "тогда; в таком случае" },
    { korean: "그런데", translation: "но; однако" },
    { korean: "그럼", translation: "в таком случае; тогда" },
    { korean: "그렇게", translation: "так" },
    { korean: "그릇", translation: "посуда; тарелка" },
    { korean: "그리", translation: "так" },
    { korean: "그리고", translation: "и; при этом; затем" },
    { korean: "그리다", translation: "рисовать" },
    { korean: "그림", translation: "рисунок, картина" },
    { korean: "그립다", translation: "хотеть видеть; тосковать" },
    { korean: "그만", translation: "хватит, достаточно" },
    { korean: "그제", translation: "позавчера" },
    { korean: "그후", translation: "после этого" },
    { korean: "극동", translation: "Дальний Восток" },
    { korean: "극복", translation: "преодоление" },
    { korean: "극복하다", translation: "преодолевать; побеждать" },
    { korean: "극장", translation: "театр" },
    { korean: "근대", translation: "новое время" },
    { korean: "근래", translation: "современность" },
    { korean: "근로자", translation: "трудящийся" },
    { korean: "근무", translation: "служба, работа" },
    { korean: "근무시간", translation: "время работы" },
    { korean: "근무하다", translation: "работать" },
    { korean: "근심", translation: "тревога, беспокойство" },
    { korean: "근처", translation: "окрестность; вблизи" },
    { korean: "글", translation: "письмо; текст" },
    { korean: "글씨", translation: "почерк" },
    { korean: "글자", translation: "буква" },
    { korean: "글쎄", translation: "да; пожалуй; впрочем" },
    { korean: "금", translation: "золото" },
    { korean: "금년", translation: "этот год" },
    { korean: "금연", translation: "запрещение курения" },
    { korean: "금요일", translation: "пятница" },
    { korean: "금속하다", translation: "поспешный, быстрый" },
    { korean: "급제하다", translation: "сдать экзамены на чин" },
    { korean: "급하다", translation: "быстрый, скорый, поспешный, срочный" },
    { korean: "기구", translation: "орудие, инструмент, аппарат, прибор" },
    { korean: "기계", translation: "машина, механизм" },
    { korean: "기념", translation: "память" },
    { korean: "기념하다", translation: "отмечать, поминать" },
    { korean: "기다", translation: "ползать" },
    { korean: "기다리다", translation: "ждать, ожидать" },
    { korean: "기대", translation: "надежда, ожидание" },
    { korean: "기대하다", translation: "надеяться, ждать" },
    { korean: "기록", translation: "запись, рекорд" },
    { korean: "기록하다", translation: "записывать" },
    { korean: "기르다", translation: "выращивать, откармливать; держать (скот); воспитывать, прививать (навыки)" },
    { korean: "기름", translation: "масло; жидкое топливо" },
    { korean: "기묘하다", translation: "странный, причудливый" },
    { korean: "기분", translation: "настроение" },
    { korean: "기쁘다", translation: "радостный, веселый" },
    { korean: "늘다", translation: "растягиваться, увеличиваться" },
    { korean: "늘리다", translation: "увеличивать" },
    { korean: "늘어나다", translation: "увеличиваться; растягиваться" },
    { korean: "늘이다", translation: "удлинять, растягивать" },
    { korean: "능력", translation: "способность" },
    { korean: "늦다", translation: "поздний; опаздывать" },
    { korean: "다", translation: "все; весь, полностью" },
    { korean: "다가서다", translation: "приближаться" },
    { korean: "다가오다", translation: "подходить, приближаться" },
    { korean: "다니다", translation: "ходить (туда-сюда)" },
    { korean: "다달이", translation: "ежемесячно" },
    { korean: "다르다", translation: "другой; быть другим" },
    { korean: "다리", translation: "1) мост; 2) нога" },
    { korean: "다만", translation: "только; лишь" },
    { korean: "다방", translation: "чайная, кафе" },
    { korean: "다스리다", translation: "править, управлять" },
    { korean: "다시", translation: "опять, снова" },
    { korean: "다음", translation: "следующий" },
    { korean: "다이어트", translation: "диета" },
    { korean: "다치다", translation: "пораниться, удариться" },
    { korean: "다행히", translation: "к счастью" },
    { korean: "닦다", translation: "1) чистить; 2) прокладывать (дорогу)" },
    { korean: "단과대학", translation: "институт; колледж" },
    { korean: "단련하다", translation: "закаляться" },
    { korean: "단어", translation: "слово" },
    { korean: "단장", translation: "туалет (приведение себя в порядок)" },
    { korean: "단정하다", translation: "опрятный, аккуратный" },
    { korean: "단체", translation: "организация, коллектив" },
    { korean: "단풍", translation: "1) клён; 2) желтые и красивые листья (осенью)" },
    { korean: "닫다", translation: "1) закрывать; 2) убегать" },
    { korean: "달", translation: "месяц, луна" },
    { korean: "달구지", translation: "телега, повозка, подвода" },
    { korean: "달라지다", translation: "отличаться; изменяться" },
    { korean: "달리", translation: "в отличие от; по-другому" },
    { korean: "달리다", translation: "бежать, бегать" },
    { korean: "닭", translation: "курица" },
    { korean: "담그다", translation: "погружать (в жидкость), мариновать, солить" },
    { korean: "담기다", translation: "ф. страд залога от 담그다" },
    { korean: "담배", translation: "табак, сигареты" },
    { korean: "답답하다", translation: "скучный, надоедливый" },
    { korean: "당", translation: "партия" },
    { korean: "당부하다", translation: "просить; наказывать, поручать" },
    { korean: "당시", translation: "тогда; в то время" },
    { korean: "당신", translation: "Вы" },
    { korean: "닿다", translation: "касаться; достигать, прибывать" },
    { korean: "대", translation: "преф. большой" },
    { korean: "대개", translation: "в основном" },
    { korean: "대기", translation: "1) атмосфера; 2) ожидание" },
    { korean: "대단히", translation: "очень" },
    { korean: "대답", translation: "ответ" },
    { korean: "대로", translation: "проспект" },
    { korean: "대륙", translation: "материк, континент" },
    { korean: "대문", translation: "ворота" },
    { korean: "대사", translation: "посол" },
    { korean: "대접", translation: "угощение, прием" },
    { korean: "대출", translation: "выдавать (в кредит), ссужать" },
    { korean: "대통령", translation: "президент (страны)" },
    { korean: "대표", translation: "представительство" },
    { korean: "대하다", translation: "относиться" },
    { korean: "대학", translation: "институт" },
    { korean: "대학교", translation: "университет" },
    { korean: "대한민국", translation: "Республика Корея" },
    { korean: "대회", translation: "съезд, конгресс" },
    { korean: "댁", translation: "Ваш дом" },
    { korean: "더", translation: "еще, более" },
    { korean: "더럽다", translation: "грязный" },
    { korean: "더불어", translation: "вместе с" },
    { korean: "더욱", translation: "еще, более" },
    { korean: "덕", translation: "добродетель" },
    { korean: "덥다", translation: "теплый, жаркий" },
    { korean: "데우다", translation: "согревать, отапливать" },
    { korean: "덮다", translation: "покрывать; закрывать" },
    { korean: "덮이다", translation: "быть покрытым (накрытым, закрытым)" },
    { korean: "데리다", translation: "брать с собой, приводить" },
    { korean: "동시", translation: "одно и то же время" },
    { korean: "동안", translation: "в течение" },
    { korean: "도", translation: "1) принцип; 2) градус; 3) провинция" },
    { korean: "도달하다", translation: "доходить, достигать" },
    { korean: "도둑", translation: "разбойник, вор" },
    { korean: "도로", translation: "дорога" },
    { korean: "도망", translation: "побег, бегство" },
    { korean: "도무지", translation: "совсем не" },
    { korean: "도서관", translation: "библиотека" },
    { korean: "도시", translation: "город" },
    { korean: "도시락", translation: "еда в коробке (на завтрак)" },
    { korean: "도움", translation: "помощь" },
    { korean: "도착", translation: "прибытие" },
    { korean: "독어", translation: "немецкий язык" },
    { korean: "독일", translation: "Германия" },
    { korean: "독", translation: "яд" },
    { korean: "돈", translation: "деньги" },
    { korean: "돈꾸러미", translation: "кошель; (связка монет)" },
    { korean: "돋다", translation: "появляться, всходить" },
    { korean: "돋우다", translation: "приподнимать" },
    { korean: "돌", translation: "камень" },
    { korean: "돌[날]", translation: "1) годовщина; 2) день рождения (у годовалого ребенка)" },
    { korean: "돌다", translation: "крутиться, вертеться" },
    { korean: "돌리다", translation: "1) крутить; вертеть; вращать; 2) возвращать" },
    { korean: "돌아가다", translation: "1) кружиться, вертеться; 2) возвращаться, уходить; 3) умирать" },
    { korean: "돌아오다", translation: "возвращаться, приходить" },
    { korean: "돕다", translation: "помогать, оказывать помощь" },
    { korean: "돗자리", translation: "циновка" },
    { korean: "동", translation: "восток" },
    { korean: "동급생", translation: "одноклассник" },
    { korean: "동네", translation: "деревня, селение" },
    { korean: "군", translation: "уезд" },
    { korean: "군대", translation: "армия" },
    { korean: "굳다", translation: "твердый, прочный" },
    { korean: "굴", translation: "пещера, нора" },
    { korean: "굵다", translation: "толстый" },
    { korean: "굶다", translation: "голодать" },
    { korean: "굽다", translation: "1) сгибать; 2) жарить" },
    { korean: "궁궐", translation: "дворец" },
    { korean: "근심하다", translation: "тревожиться, беспокоиться" },
    { korean: "권투", translation: "бокс" },
    { korean: "권하다", translation: "предлагать" },
    { korean: "귀국", translation: "возвращение на родину" },
    { korean: "귀엽다", translation: "милый, симпатичный" },
    { korean: "귀중하다", translation: "дорогой, благородный" },
    { korean: "규모", translation: "масштаб, размер" },
    { korean: "규율", translation: "порядок, дисциплина" },
    { korean: "규칙", translation: "правило" },
    { korean: "귤", translation: "цитрусовые (мандарин, апельсин)" },
    { korean: "그", translation: "(э)тот" },
    { korean: "그것", translation: "(э)то; он, она, оно" },
    { korean: "그냥", translation: "1) в таком виде (так), как есть; 2) как и раньше, по-прежнему; 3) просто; как ни в чем не бывало" },
    { korean: "그녀", translation: "она" },
    { korean: "그늘", translation: "тень" },
    { korean: "그대로", translation: "так; в таком виде" },
    { korean: "그래", translation: "да; так; хорошо" },
    { korean: "그래도", translation: "но; однако" },
    { korean: "그래서", translation: "поэтому" },
    { korean: "그러나", translation: "но; однако" },
    { korean: "그러면", translation: "тогда; в таком случае" },
    { korean: "그런데", translation: "но; однако" },
    { korean: "그럼", translation: "в таком случае; тогда" },
    { korean: "그렇게", translation: "так" },
    { korean: "그릇", translation: "посуда; тарелка" },
    { korean: "그리", translation: "так" },
    { korean: "그리고", translation: "и; при этом; затем" },
    { korean: "그리다", translation: "рисовать" },
    { korean: "그림", translation: "рисунок, картина" },
    { korean: "그립다", translation: "хотеть видеть; тосковать" },
    { korean: "그만", translation: "хватит, достаточно" },
    { korean: "그제", translation: "позавчера" },
    { korean: "그후", translation: "после этого" },
    { korean: "극동", translation: "Дальний Восток" },
    { korean: "극복", translation: "преодоление" },
    { korean: "극장", translation: "театр" },
    { korean: "근대", translation: "новое время" },
    { korean: "근래", translation: "современность" },
    { korean: "근로자", translation: "трудящийся" },
    { korean: "근무", translation: "служба, работа" },
    { korean: "근심", translation: "тревога, беспокойство" },
    { korean: "근처", translation: "окрестность; вблизи" },
    { korean: "글", translation: "письмо; текст" },
    { korean: "글쎄", translation: "да; пожалуй; впрочем" },
    { korean: "금", translation: "золото" },
    { korean: "금년", translation: "этот год" },
    { korean: "금연", translation: "запрещение курения" },
    { korean: "금요일", translation: "пятница" },
    { korean: "급속하다", translation: "поспешный, быстрый" },
    { korean: "급제하다", translation: "сдать экзамены на чин" },
    { korean: "급하다", translation: "быстрый, скорый, поспешный, срочный" },
    { korean: "기구", translation: "орудие, инструмент, аппарат, прибор" },
    { korean: "기계", translation: "машина, механизм" },
    { korean: "기념", translation: "память" },
    { korean: "기다", translation: "ползать" },
    { korean: "기다리다", translation: "ждать, ожидать" },
    { korean: "기대", translation: "надежда, ожидание" },
    { korean: "기록", translation: "запись, рекорд" },
    { korean: "기르다", translation: "1) выращивать, откармливать; держать (скот); 2) воспитывать, прививать (навыки)" },
    { korean: "기름", translation: "масло; жидкое топливо" },
    { korean: "기묘하다", translation: "странный, причудливый" },
    { korean: "기분", translation: "настроение" },
    { korean: "기쁘다", translation: "радостный, веселый" },
    { korean: "나타나다", translation: "появляться" },
    { korean: "나타내다", translation: "выявлять, отражать" },
    { korean: "낙제하다", translation: "провалиться (на экзам.)" },
    { korean: "낚시", translation: "удочка" },
    { korean: "난민", translation: "беженец" },
    { korean: "날", translation: "день" },
    { korean: "날다", translation: "летать" },
    { korean: "날리다", translation: "1) запускать (в воздух); 2) быть унесенным (ветром)" },
    { korean: "날씨", translation: "погода" },
    { korean: "남", translation: "чужой" },
    { korean: "남기다", translation: "оставлять" },
    { korean: "남다", translation: "оставаться" },
    { korean: "남북", translation: "юг и север" },
    { korean: "남자", translation: "мужчина" },
    { korean: "남쪽", translation: "юг, южная сторона" },
    { korean: "남탕", translation: "мужское отделение (в бане)" },
    { korean: "남편", translation: "муж" },
    { korean: "남해", translation: "Южное море" },
    { korean: "낫다", translation: "быть лучше; улучшаться" },
    { korean: "낮", translation: "день" },
    { korean: "낮다", translation: "низкий" },
    { korean: "낯", translation: "лицо" },
    { korean: "낳다", translation: "родить(ся)" },
    { korean: "내", translation: "я; мой" },
    { korean: "내다", translation: "ф. побуд. залога от 나다" },
    { korean: "내다보다", translation: "выглядывать (в окно)" },
    { korean: "내리다", translation: "спускать(ся); падать" },
    { korean: "내리우다", translation: "спускать, опускать" },
    { korean: "내버리다", translation: "выбрасывать" },
    { korean: "내보내다", translation: "отправлять" },
    { korean: "내용", translation: "содержание" },
    { korean: "내일", translation: "завтра" },
    { korean: "내주", translation: "следующая неделя" },
    { korean: "냉수", translation: "холодная вода" },
    { korean: "냉장고", translation: "холодильник" },
    { korean: "냉탕", translation: "холодная ванна" },
    { korean: "네", translation: "ты" },
    { korean: "너무", translation: "слишком, чересчур" },
    { korean: "느릿느릿", translation: "плавно, медленно" },
    { korean: "널리", translation: "широко" },
    { korean: "넓다", translation: "широкий" },
    { korean: "넓이", translation: "ширина" },
    { korean: "넘다", translation: "переходить, переваливать" },
    { korean: "넘어지다", translation: "рухнуть" },
    { korean: "넣다", translation: "ставить, класть (внутрь)" },
    { korean: "네", translation: "твой" },
    { korean: "해", translation: "год" },
    { korean: "노동", translation: "труд" },
    { korean: "노랑나비", translation: "желтая бабочка (капустинца)" },
    { korean: "노래", translation: "песня" },
    { korean: "노인", translation: "старик" },
    { korean: "녹다", translation: "таять" },
    { korean: "노임", translation: "зарплата" },
    { korean: "논", translation: "орошаемое (заливное) поле" },
    { korean: "논문", translation: "статья, публикация" },
    { korean: "놀다", translation: "гулять, веселиться" },
    { korean: "놀리다", translation: "ф. побуд. зал. от 놀다" },
    { korean: "놀이", translation: "игра" },
    { korean: "놈", translation: "презр. человек, тип" },
    { korean: "농구", translation: "баскетбол" },
    { korean: "농담", translation: "шутка" },
    { korean: "농부", translation: "крестьянин" },
    { korean: "농사", translation: "сельхозработы" },
    { korean: "농장", translation: "ферма" },
    { korean: "농촌", translation: "деревня" },
    { korean: "높다", translation: "высокий" },
    { korean: "높이", translation: "1) высоко; 2) высота" },
    { korean: "놓다", translation: "класть, ставить" },
    { korean: "놓치다", translation: "упускать" },
    { korean: "누구", translation: "кто" },
    { korean: "누더기", translation: "лохмотья" },
    { korean: "누르다", translation: "1) желтый; 2) давить, жать" },
    { korean: "누나", translation: "сестра" },
    { korean: "눈", translation: "1) глаз; 2) снег" },
    { korean: "눈물", translation: "слезы" },
    { korean: "눈치", translation: "смекалка, догадливость" },
    { korean: "눕다", translation: "ложиться" },
    { korean: "뉴", translation: "дюжина" },
    { korean: "느끼다", translation: "чувствовать" },
    { korean: "느낌", translation: "чувство" },
    { korean: "늘", translation: "всегда, постоянно" },
    { korean: "따뜻하다", translation: "теплый" },
    { korean: "따라", translation: "вслед за" },
    { korean: "따르다", translation: "следовать за кем-л." },
    { korean: "따르릉", translation: "обр. слово, подражание грохоту, взрыву" },
    { korean: "따지다", translation: "докапываться, разбираться" },
    { korean: "딸", translation: "дочь" },
    { korean: "땀", translation: "пот" },
    { korean: "땅", translation: "суша, земля, почва" },
    { korean: "때", translation: "время, пора" },
    { korean: "때때로", translation: "иногда, время от времени" },
    { korean: "때리다", translation: "бить, избивать, ударять" },
    { korean: "때문", translation: "причина" },
    { korean: "떠나다", translation: "отправляться; оставлять, покидать" },
    { korean: "떠들다", translation: "шуметь, кричать" },
    { korean: "떡", translation: "рисовый паровой хлебец" },
    { korean: "떨다", translation: "трястись, дрожать" },
    { korean: "떨어지다", translation: "падать, опадать" },
    { korean: "떨치다", translation: "приобретать известность" },
    { korean: "또", translation: "снова, опять; и, еще" },
    { korean: "뚜뚜하다", translation: "ясный; отчетливый; четкий" },
    { korean: "뛰다", translation: "прыгать, подпрыгивать; подскакивать, скакать; бежать" },
    { korean: "뜨겁다", translation: "горячий, жаркий" },
    { korean: "뜨다", translation: "1) всходить (о солнце); 2) открывать (глаза)" },
    { korean: "뜯다", translation: "рвать, срывать" },
    { korean: "뜻", translation: "значение, смысл; воля, замысел" },
    { korean: "라디오", translation: "радио" },
    { korean: "러시아", translation: "Россия" },
    { korean: "로봇", translation: "робот" },
    { korean: "리", translation: "1) ли (мера длины, равная 0,393 м); 2) основание, повод" },
    { korean: "마다", translation: "каждый" },
    { korean: "마당", translation: "двор; арена" },
    { korean: "마련하다", translation: "подготовить, устроить" },
    { korean: "마르다", translation: "1) сухой; 2) сохнуть, высыхать" },
    { korean: "마리", translation: "сч. сл. для животных" },
    { korean: "마시다", translation: "пить" },
    { korean: "마을", translation: "деревня, поселок" },
    { korean: "마음", translation: "душа" },
    { korean: "마중하다", translation: "встречать" },
    { korean: "마지막", translation: "последний" },
    { korean: "마차", translation: "телега, экипаж" },
    { korean: "마찬가지", translation: "одинаковый, такой же" },
    { korean: "마치", translation: "словно, будто" },
    { korean: "마치다", translation: "кончать(cя), заканчивать(cя)" },
    { korean: "마침", translation: "как раз, кстати, именно" },
    { korean: "마침내", translation: "наконец" },
    { korean: "막", translation: "занавес" },
    { korean: "막내", translation: "младший" },
    { korean: "막다", translation: "преграждать, загораживать" },
    { korean: "만", translation: "десять тысяч" },
    { korean: "만나다", translation: "встречать(cя)" },
    { korean: "만년필", translation: "авторучка" },
    { korean: "만두", translation: "пельмени" },
    { korean: "만들다", translation: "делать, изготавливать" },
    { korean: "만약", translation: "если; допустим (предположим), что" },
    { korean: "만원경", translation: "бинокль" },
    { korean: "만족하다", translation: "быть удовлетворенным" },
    { korean: "만지다", translation: "щупать, ощупывать" },
    { korean: "많다", translation: "многочисленный; много" },
    { korean: "맏", translation: "преф. старший" },
    { korean: "말", translation: "1) конь; 2) слово; 3) язык" },
    { korean: "말", translation: "суф. конец" },
    { korean: "말씀", translation: "вежд слово, речь" },
    { korean: "말하다", translation: "говорить, рассказывать" },
    { korean: "맑다", translation: "ясный, чистый; прозрачный" },
    { korean: "맛", translation: "вкус" },
    { korean: "맞다", translation: "1) подходить, соответствовать; 2) встречать, отмечать; 3) попадать (под дождь); 4) ударяться" },
    { korean: "맞이하다", translation: "встречать; принимать" },
    { korean: "맞춤법", translation: "орфография" },
    { korean: "맡기다", translation: "поручать (кому-л.); доверять, вверять" },
    { korean: "맡다", translation: "брать на себя (ответственность)" },
    { korean: "매다", translation: "связывать, завязывать" },
    { korean: "매몰차다", translation: "бессердечный; лютый, свирепый" },
    { korean: "매연", translation: "дым; выхлоп (газов)" },
    { korean: "매우", translation: "очень" },
    { korean: "매일", translation: "каждый день" },
    { korean: "맥주", translation: "пиво" },
    { korean: "맵다", translation: "острый (о пище)" },
    { korean: "머리", translation: "голова" },
    { korean: "머무르다", translation: "останавливаться" },
    { korean: "먹다", translation: "есть; пить" },
    { korean: "먹물", translation: "жидкая тушь" },
    { korean: "먹히다", translation: "быть съеденным" },
    { korean: "먼저", translation: "сначала; раньше" },
    { korean: "먼지", translation: "пыль" },
    { korean: "멀다", translation: "далекий, дальний; давний" },
    { korean: "멀리", translation: "далеко" },
    { korean: "멀어지다", translation: "удаляться" },
    { korean: "멈추다", translation: "прекращаться, переставать, останавливаться" },
    { korean: "멍멍", translation: "обр. слово подражание лаю собаки" },
    { korean: "멎다", translation: "прекращаться, заканчиваться" },
    { korean: "메마르다", translation: "сухой, увядший; невыразительный, тусклый; вянуть" },
    { korean: "메모하다", translation: "запоминать; помечать" },
    { korean: "메우다", translation: "заполнять" },
    { korean: "무겁다", translation: "тяжелый" },
    { korean: "무게", translation: "вес" },
    { korean: "무너지다", translation: "рушиться, обваливаться" },
    { korean: "무덥다", translation: "душный" },
    { korean: "무서움", translation: "страх" },
    { korean: "무섭다", translation: "страшный" },
    { korean: "무슨", translation: "какой, который" },
    { korean: "무시하다", translation: "игнорировать, пренебрегать" },
    { korean: "무엇", translation: "что; что-то" },
    { korean: "무지개", translation: "радуга" },
    { korean: "무척", translation: "очень, чрезмерно, безмерно" },
    { korean: "묵다", translation: "останавливаться на ночлег; оставаться погостить" },
    { korean: "묶음", translation: "связка, вязанка, сноп" },
    { korean: "문", translation: "дверь, ворота" },
    { korean: "문법", translation: "грамматика" },
    { korean: "문안", translation: "осведомление о здоровье" },
    { korean: "문장", translation: "предложение" },
    { korean: "문제", translation: "вопрос, проблема, задача" },
    { korean: "문화", translation: "культура" },
    { korean: "묻다", translation: "1) спрашивать; 2) зарывать, закапывать; хоронить" },
    { korean: "물", translation: "вода" },
    { korean: "물건", translation: "вещь, предмет" },
    { korean: "물고기", translation: "рыба" },
    { korean: "물다", translation: "1) платить; 2) брать в рот; кусать, жалить" },
    { korean: "물들다", translation: "окрашиваться" },
    { korean: "물론", translation: "конечно, безусловно" },
    { korean: "물리다", translation: "быть укушенным (ужаленным)" },
    { korean: "물리학", translation: "физика" },
    { korean: "물음", translation: "вопрос" },
    { korean: "묵히다", translation: "ценить (в груди)" },
    { korean: "미", translation: "красота" },
    { korean: "미국", translation: "Америка" },
    { korean: "미끄럽다", translation: "скользкий" },
    { korean: "미래", translation: "будущее, грядущее" },
    { korean: "미리", translation: "заранее" },
    { korean: "미소", translation: "улыбка" },
    { korean: "미술", translation: "изобразительное искусство" },
    { korean: "미스", translation: "мисс, госпожа" },
    { korean: "미어지다", translation: "продираться, разрываться" },
    { korean: "미워하다", translation: "не любить; не нравиться" },
    { korean: "미인", translation: "красавица" },
    { korean: "미터", translation: "метр" },
    { korean: "민망하다", translation: "жалкий, досадный" },
    { korean: "믿다", translation: "верить" },
    { korean: "믿음", translation: "вера" },
    { korean: "밀다", translation: "толкать, отталкивать" },
    { korean: "밀리다", translation: "быть вытесненным; хлынуть потоком" },
    { korean: "밉다", translation: "противный, омерзительный" },
    { korean: "밑", translation: "нижняя часть; снизу" },
    { korean: "바깥", translation: "внешний, наружный" },
    { korean: "바꾸다", translation: "менять, обменивать" },
    { korean: "바뀌다", translation: "меняться, заменяться" },
    { korean: "바다", translation: "море" },
    { korean: "바닥", translation: "1) пол; 2) полотно (дороги), асфальт; 3) днище, дно" },
    { korean: "바닷가", translation: "берег моря" },
    { korean: "바닷물", translation: "морская вода" },
    { korean: "바라다", translation: "надеяться; желать, хотеть" },
    { korean: "바라보다", translation: "смотреть прямо; смотреть вдаль" },
    { korean: "바람", translation: "1) ветер; 2) сл. имя" },
    { korean: "바로", translation: "точно, прямо, как раз, именно" },
    { korean: "바르다", translation: "1) прямой; правильный; честный 2) мазать, намазывать" },
    { korean: "바보", translation: "дурак" },
    { korean: "바쁘다", translation: "быть занятым; спешить" },
    { korean: "바위", translation: "скала; гора" },
    { korean: "바윗길", translation: "горная тропа" },
    { korean: "박물관", translation: "музей" },
    { korean: "바짝", translation: "обр. сл. царапать, скрести" },
    { korean: "박해", translation: "притеснение, преследование" },
    { korean: "밖", translation: "вне (чего-л.); кроме" },
    { korean: "반", translation: "1) группа, класс; 2) половина" },
    { korean: "반가워하다", translation: "радоваться" },
    { korean: "반갑다", translation: "приятный, радостный" },
    { korean: "반기다", translation: "радовать (кого-л.)" },
    { korean: "반도", translation: "полуостров" },
    { korean: "반드시", translation: "непременно" },
    { korean: "반복", translation: "повторение" },
    { korean: "반찬", translation: "гарнир (к мясу)" },
    { korean: "받다", translation: "брать, получать" },
    { korean: "받들다", translation: "поддерживать; почитать" },
    { korean: "받아들이다", translation: "принимать, воспринимать, заимствовать" },
    { korean: "발", translation: "нога (ступня)" },
    { korean: "발걸음", translation: "шаг" },
    { korean: "발견하다", translation: "обнаруживать" },
    { korean: "발걸", translation: "1) шаг 2) наплыв, поток" },
    { korean: "발음", translation: "произношение" },
    { korean: "발자국", translation: "след (ноги)" },
    { korean: "발전", translation: "развитие, развертывание" },
    { korean: "발표", translation: "публикация, сообщение" },
    { korean: "밝다", translation: "ясный, яркий" },
    { korean: "밝히다", translation: "освещать, озарять" },
    { korean: "밟다", translation: "ступать, наступать, топтать" },
    { korean: "밤", translation: "1) ночь; 2) каштан" },
    { korean: "밥", translation: "рис; пища, еда" },
    { korean: "방", translation: "комната" },
    { korean: "방문", translation: "посещение, визит" },
    { korean: "방법", translation: "метод, способ; средство" },
    { korean: "방송", translation: "[теле-радио]передача" },
    { korean: "방식", translation: "метод, способ, система" },
    { korean: "방안", translation: "предложение, проект, план" },
    { korean: "방학", translation: "каникулы" },
    { korean: "방해", translation: "препятствие, помеха" },
    { korean: "밭", translation: "(суходольное) поле" },
    { korean: "배", translation: "1) живот; 2) лодка; 3) груша; 4) раз" },
    { korean: "배우", translation: "артист, актер" },
    { korean: "배우다", translation: "учить(ся)" },
    { korean: "백성", translation: "простолюдин" },
    { korean: "백화점", translation: "универсальный магазин" },
    { korean: "뱉다", translation: "плевать, выплевывать" },
    { korean: "버들", translation: "ива" },
    { korean: "버릇", translation: "привычка" },
    { korean: "버리다", translation: "бросать, оставлять" },
    { korean: "버스", translation: "автобус" },
    { korean: "번", translation: "раз" },
    { korean: "번역", translation: "перевод" },
    { korean: "번쩍", translation: "обр. слово резко, быстро" },
    { korean: "번호", translation: "номер, шифр" },
    { korean: "벌", translation: "наказание, кара" },
    { korean: "벌다", translation: "зарабатывать" },
    { korean: "벌떡", translation: "обр. слово вскакивать" },
    { korean: "벌레", translation: "насекомое" },
    { korean: "벌리다", translation: "образовывать (щель); раскрывать (рот)" },
    { korean: "벌써", translation: "уже" },
    { korean: "벌", translation: "поле, равнина" },
    { korean: "범", translation: "тигр" },
    { korean: "범람하다", translation: "разливаться, выходить из берегов" },
    { korean: "범인", translation: "преступник" },
    { korean: "법", translation: "правило, закон" },
    { korean: "법칙", translation: "правило, закон, закономерность" },
    { korean: "벗", translation: "друг, соратник" },
    { korean: "벗다", translation: "снимать (одежду), раздеться" },
    { korean: "벙어리", translation: "немой" },
    { korean: "베다", translation: "резать; жать; косить" },
    { korean: "베풀다", translation: "учреждать, создавать, сооружать; устраивать (обед, ужин)" },
    { korean: "벼슬", translation: "должность, чин" },
    { korean: "벽", translation: "стена" },
    { korean: "변두리", translation: "край, окраина" },
    { korean: "별", translation: "звезда" },
    { korean: "별일", translation: "неожиданность, происшествие" },
    { korean: "특히", translation: "особенно" },
    { korean: "별장", translation: "загородный дом; дача" },
    { korean: "병", translation: "болезнь" },
    { korean: "병상", translation: "болезненное состояние; состояние больного" },
    { korean: "병아리", translation: "цыпленок" },
    { korean: "병원", translation: "больница, госпиталь" },
    { korean: "보다", translation: "смотреть; видеть" },
    { korean: "보답하다", translation: "отблагодарить" },
    { korean: "보이다", translation: "1) быть видным, виднеться 2) казаться" },
    { korean: "보존", translation: "сохранение; консервация" },
    { korean: "보충", translation: "дополнение" },
    { korean: "보통", translation: "1) обычный, обыкновенный; 2) обычно, как правило" },
    { korean: "보호", translation: "защита, охрана" },
    { korean: "복습", translation: "повторение" },
    { korean: "복잡하다", translation: "сложный, запутанный" },
    { korean: "볶다", translation: "жарить, тушить" },
    { korean: "본", translation: "преф. 1) основной, коренной; 2) этот, данный" },
    { korean: "본문", translation: "текст" },
    { korean: "봄", translation: "весна" },
    { korean: "봉", translation: "вершина" },
    { korean: "봉투", translation: "конверт" },
    { korean: "부끄럽다", translation: "стыдливый, застенчивый" },
    { korean: "부드럽다", translation: "мягкий (на ощупь)" },
    { korean: "부딪치다", translation: "удариться, столкнуться" },
    { korean: "부럽다", translation: "испытывать зависть" },
    { korean: "부르다", translation: "1) звать, приглашать; 2) называть" },
    { korean: "부름", translation: "призыв, зов" },
    { korean: "부모", translation: "родители" },
    { korean: "부분", translation: "часть" },
    { korean: "부상", translation: "рана" },
    { korean: "부엌", translation: "кухня" },
    { korean: "부인", translation: "1) замужняя женщина; 2) вежд. Ваша супруга" },
    { korean: "부자", translation: "богач" },
    { korean: "부지런하다", translation: "трудолюбивый" },
    { korean: "부채", translation: "веер" },
    { korean: "붙이다", translation: "1) прилипать, приклеивать; 2) посылать, отправлять" },
    { korean: "부탁", translation: "просьба, поручение" },
    { korean: "북극점", translation: "Северный полюс" },
    { korean: "분", translation: "1) вежд. человек; 2) минута" },
    { korean: "분명하다", translation: "ясный, явный, определенный, отчетливый" },
    { korean: "분위기", translation: "атмосфера" },
    { korean: "분주하다", translation: "занятой, спешный" },
    { korean: "불", translation: "огонь, пламя; свет" },
    { korean: "불굴", translation: "несгибаемый, непреклонный" },
    { korean: "불다", translation: "дуть, раздувать" },
    { korean: "불리다", translation: "1) называться, прозываться; 2) быть слушным (ветром)" },
    { korean: "불빛", translation: "отсвет, отблеск" },
    { korean: "불어나다", translation: "наполняться, разбухать" },
    { korean: "불편하다", translation: "неудобный" },
    { korean: "붙다", translation: "приставать, прилипать" },
    { korean: "붙이다", translation: "см 붙이다" },
    { korean: "비", translation: "1) дождь; 2) сумма стоимость" },
    { korean: "비극", translation: "трагедия" },
    { korean: "비누", translation: "мыло" },
    { korean: "비다", translation: "пустой, порожний; свободный" },
    { korean: "비뚤어지다", translation: "искривляться" },
    { korean: "비록", translation: "хотя" },
    { korean: "비밀", translation: "тайна, секрет" },
    { korean: "비싸다", translation: "дорогой" },
    { korean: "비유하다", translation: "сопоставлять" },
    { korean: "비행기", translation: "самолет" },
    { korean: "빌리다", translation: "давать в долг (в аренду); занимать" },
    { korean: "빗", translation: "гребень, расческа" },
    { korean: "빗물", translation: "дождевая вода" },
    { korean: "방긋방긋", translation: "обр. слово улыбаться" },
    { korean: "빚", translation: "долг" },
    { korean: "빛", translation: "цвет, окраска, расцветка" },
    { korean: "빠르다", translation: "быстрый" },
    { korean: "빠지다", translation: "падать, выпадать; проваливаться" },
    { korean: "빨개지다", translation: "заливаться румянцем" },
    { korean: "빨리", translation: "быстро" },
    { korean: "빼다", translation: "удалять" },
    { korean: "빼앗다", translation: "отбирать, отнимать, присваивать, захватывать" },
    { korean: "빼앗기다", translation: "страд залог от 빼앗다" },
    { korean: "뻗다", translation: "тянуться, простираться" },
    { korean: "뽑다", translation: "вытаскивать, выдергивать, вырывать, выбирать" },
    { korean: "뿌리", translation: "корень" },
    { korean: "뿌옇다", translation: "посереть, побледнеть" },
    { korean: "뿜다", translation: "извергать, испускать" },
    { korean: "뿜기다", translation: "ф. страд залога от 뿜다" },
    { korean: "사건", translation: "событие, происшествие" },
    { korean: "사고", translation: "происшествие; несчастный случай, авария" },
    { korean: "사과", translation: "яблоко" },
    { korean: "사다", translation: "покупать" },
    { korean: "사라지다", translation: "исчезать, пропадать" },
    { korean: "사람", translation: "человек" },
    { korean: "사랑", translation: "любовь" },
    { korean: "사료", translation: "корм, фураж" },
    { korean: "사무실", translation: "кабинет, канцелярия, офис" },
    { korean: "사방", translation: "четыре стороны света; вокруг, всюду, везде, повсеместно" },
    { korean: "사범", translation: "педагогический" },
    { korean: "사상", translation: "мысль, идея; идеология" },
    { korean: "사실", translation: "факт; реальность, действительность" },
    { korean: "사업", translation: "работа, дело" },
    { korean: "사용하다", translation: "употреблять, использовать, применять" },
    { korean: "사의", translation: "признательность, благодарность" },
    { korean: "사이", translation: "промежуток, интервал; отношение, взаимоотношения" },
    { korean: "사인", translation: "подпись, роспись" },
    { korean: "사자", translation: "лев" },
    { korean: "사장", translation: "директор (президент) компании" },
    { korean: "사전", translation: "словарь" },
    { korean: "사정", translation: "обстоятельства; положение дел; обстановка" },
    { korean: "사진", translation: "фотография" },
    { korean: "사촌", translation: "двоюродный (брат); двоюродная (сестра)" },
    { korean: "사회", translation: "общество" },
    { korean: "산", translation: "гора" },
    { korean: "산림", translation: "лес (покрывающий горы)" },
    { korean: "산보", translation: "прогулка" },
    { korean: "산업", translation: "промышленность" },
    { korean: "살", translation: "1) сч. сл. для обозначения возраста; 2) мясо, мышца" },
    { korean: "살다", translation: "жить; обитать" },
    { korean: "솔랑솔랑", translation: "обр слово дуть (о легком ветерке)" },
    { korean: "살리다", translation: "оживлять; спасать" },
    { korean: "살림", translation: "домашнее хозяйство; жизнь" },
    { korean: "살살", translation: "обр слово незаметно, тихо, осторожно, слегка" },
    { korean: "살해", translation: "убийство" },
    { korean: "삶", translation: "жизнь" },
    { korean: "삶다", translation: "варить" },
    { korean: "삼국", translation: "три государства" },
    { korean: "삼년", translation: "три года" },
    { korean: "삼다", translation: "считать, рассматривать (кого-либо чем-либо)" },
    { korean: "삼촌", translation: "брат отца; дядя" },
    { korean: "상", translation: "стол" },
    { korean: "상당하다", translation: "достаточный, приличный" },
    { korean: "상대방", translation: "другая (противная) сторона; противник, партнер" },
    { korean: "상대자", translation: "партнер" },
    { korean: "상보", translation: "скатерть" },
    { korean: "상복", translation: "траурное одеяние" },
    { korean: "상사", translation: "вышестоящий начальник" },
    { korean: "상승", translation: "подъем; рост" },
    { korean: "상영", translation: "демонстрация (фильма)" },
    { korean: "상의하다", translation: "согласовывать; совещаться, обсуждать" },
    { korean: "상점", translation: "магазин" },
    { korean: "상위", translation: "верхнее (первое) место" },
    { korean: "상징", translation: "символ" },
    { korean: "상품", translation: "товар" },
    { korean: "새", translation: "1) птица; 2) новый" },
    { korean: "새기다", translation: "высекать, выбивать" },
    { korean: "새까맣다", translation: "черный (как смоль)" },
    { korean: "새로", translation: "вновь, заново, снова" },
    { korean: "새롭다", translation: "новый, свежий" },
    { korean: "색", translation: "цвет" },
    { korean: "샘", translation: "родник, ключ" },
    { korean: "생각", translation: "дума, мысль; воспоминание" },
    { korean: "생기다", translation: "появляться, возникать" },
    { korean: "생물학", translation: "биология" },
    { korean: "생산", translation: "производство" },
    { korean: "생생히", translation: "живо, ясно, отчетливо" },
    { korean: "생일", translation: "день рождения" },
    { korean: "생활", translation: "жизнь, существование" },
    { korean: "서늘하다", translation: "прохладный; свежий" },
    { korean: "서다", translation: "вставать, стоять" },
    { korean: "서두르다", translation: "торопиться, спешить" },
    { korean: "서로", translation: "вместе, взаимно" },
    { korean: "서류", translation: "документы, бумаги" },
    { korean: "서리", translation: "иней" },
    { korean: "서명", translation: "подпись" },
    { korean: "서점", translation: "книжный магазин" },
    { korean: "서쪽", translation: "запад" },
    { korean: "서해", translation: "западное море" },
    { korean: "석가모니", translation: "Шакьямуни" },
    { korean: "석굴", translation: "каменная пещера" },
    { korean: "석탑", translation: "каменная пагода" },
    { korean: "섞다", translation: "смешивать, подмешивать" },
    { korean: "섞이다", translation: "быть смешанным (подмешанным); смешиваться" },
    { korean: "선", translation: "линия, черта" },
    { korean: "선거", translation: "выборы" },
    { korean: "선물", translation: "подарок, дар" },
    { korean: "선비", translation: "конф. ученик" },
    { korean: "선생", translation: "учитель" },
    { korean: "선수", translation: "спортсмен" },
    { korean: "선원", translation: "экипаж (судна); член экипажа, моряк" },
    { korean: "설립", translation: "основание, учреждение" },
    { korean: "설명", translation: "объяснение, разъяснение, толкование" },
    { korean: "설탕", translation: "сахарный песок" },
    { korean: "섬", translation: "остров" },
    { korean: "섭섭하다", translation: "грустный; досадный" },
    { korean: "성격", translation: "характер" },
    { korean: "성공", translation: "успех, достижение" },
    { korean: "성과", translation: "результат, достижение, успех" },
    { korean: "성당", translation: "христианский храм" },
    { korean: "성인", translation: "святой (человек)" },
    { korean: "성적", translation: "достижение, успех" },
    { korean: "성탄절", translation: "ред. Рождество" },
    { korean: "성화", translation: "церковная живопись; икона" },
    { korean: "세", translation: "1) суб. налог 2) сч. слово" },
    { korean: "세계", translation: "мир" },
    { korean: "세관", translation: "таможня" },
    { korean: "세다", translation: "1) сильный; 2) считать" },
    { korean: "세력", translation: "сила, мощь" },
    { korean: "세미나", translation: "семинар" },
    { korean: "세상", translation: "мир, свет" },
    { korean: "세수", translation: "умывание" },
    { korean: "세우다", translation: "устанавливать, ставить; возводить; учреждать, создавать" },
    { korean: "세월", translation: "время, период; годы" },
    { korean: "세차다", translation: "очень сильный, очень мощный" },
    { korean: "셈", translation: "[под]счет" },
    { korean: "소", translation: "вол, корова" },
    { korean: "소개", translation: "знакомство" },
    { korean: "소금", translation: "соль" },
    { korean: "소나기", translation: "ливень, проливной дождь" },
    { korean: "소나무", translation: "сосна" },
    { korean: "소년", translation: "подросток; молодежь" },
    { korean: "소리", translation: "1) звук 2) голос" },
    { korean: "소망", translation: "давнее желание, давняя мечта; чаяние" },
    { korean: "소문", translation: "слухи, молва" },
    { korean: "소설", translation: "прозаическое произведение; роман" },
    { korean: "소원", translation: "желание" },
    { korean: "소중하다", translation: "ценный, дорогой" },
    { korean: "소포", translation: "посылка" },
    { korean: "소홀히", translation: "невнимательно, пренебрежительно" },
    { korean: "속", translation: "внутренняя часть чего-либо" },
    { korean: "속다", translation: "обмануться, обознаться" },
    { korean: "속도", translation: "скорость, темп" },
    { korean: "속이다", translation: "обмануть (кого-либо)" },
    { korean: "손", translation: "рука (кисть)" },
    { korean: "손님", translation: "гость" },
    { korean: "손바닥", translation: "ладонь" },
    { korean: "손자", translation: "внук" },
    { korean: "송골매", translation: "коршун" },
    { korean: "쇠", translation: "железо, металл" },
    { korean: "쇠고기", translation: "говядина" },
    { korean: "쇼핑", translation: "шопинг, покупки" },
    { korean: "수", translation: "число, количество" },
    { korean: "수고하다", translation: "трудиться" },
    { korean: "수도", translation: "1) водопровод; 2) столица" },
    { korean: "수돗물", translation: "водопроводная вода" },
    { korean: "수리", translation: "ремонт" },
    { korean: "수수께끼", translation: "загадка, головоломка" },
    { korean: "수술", translation: "операция" },
    { korean: "수업", translation: "урок" },
    { korean: "수영", translation: "плавание" },
    { korean: "수입", translation: "1) импорт; 2) доход" },
    { korean: "수저", translation: "ложка и палочки для еды" },
    { korean: "수준", translation: "уровень" },
    { korean: "수첩", translation: "записная книжка, блокнот" },
    { korean: "수출", translation: "вывоз, экспорт" },
    { korean: "수평선", translation: "горизонт" },
    { korean: "수학", translation: "1) математика; 2) обучение, учеба" },
    { korean: "수행", translation: "осуществление, выполнение" },
    { korean: "숙이다", translation: "наклонить, опустить, погрузить (голову)" },
    { korean: "숙제", translation: "домашнее задание" },
    { korean: "순간", translation: "момент, мгновение" },
    { korean: "순종하다", translation: "повиноваться, подчиняться" },
    { korean: "술", translation: "вино; водка" },
    { korean: "술상", translation: "стол, уставленный бутылками с водкой и закусками" },
    { korean: "숨", translation: "дыхание" },
    { korean: "숨기다", translation: "прятать, скрывать" },
    { korean: "숨다", translation: "прятаться, скрываться" },
    { korean: "숫자", translation: "число" },
    { korean: "숲", translation: "лес, чаща" },
    { korean: "쉬다", translation: "1) отдыхать; 2) дышать" },
    { korean: "쉽다", translation: "легкий; простой" },
    { korean: "스님", translation: "1) наставник; 2) монах" },
    { korean: "스승", translation: "учитель, наставник" },
    { korean: "스케이트", translation: "коньки" },
    { korean: "스키", translation: "лыжи" },
    { korean: "습득", translation: "овладение, освоение" },
    { korean: "승리", translation: "победа" },
    { korean: "승용차", translation: "легковой автомобиль" },
    { korean: "시", translation: "время; час" },
    { korean: "시각", translation: "момент; время" },
    { korean: "시간", translation: "время; час" },
    { korean: "시계", translation: "часы" },
    { korean: "시골", translation: "провинция, периферия" },
    { korean: "시기", translation: "время, период" },
    { korean: "시끄럽다", translation: "шумный, суетливый" },
    { korean: "시내", translation: "центр города" },
    { korean: "시도", translation: "намерение, попытка" },
    { korean: "시선", translation: "взгляд" },
    { korean: "시원하다", translation: "свежий, прохладный" },
    { korean: "시인", translation: "поэт" },
    { korean: "시작", translation: "начало" },
    { korean: "시장", translation: "1) базар, рынок 2) мэр" },
    { korean: "시장하다", translation: "быть голодным, проголодаться" },
    { korean: "시절", translation: "период жизни" },
    { korean: "시청", translation: "городская управа, мэрия" },
    { korean: "시키다", translation: "заставлять (позволять) делать что-либо; велеть; заказывать" },
    { korean: "시합", translation: "состязание, соревнование" },
    { korean: "시험", translation: "экзамен" },
    { korean: "식구", translation: "член семьи; едок" },
    { korean: "식당", translation: "столовая" },
    { korean: "식민지", translation: "колония" },
    { korean: "식사", translation: "еда, пища" },
    { korean: "신", translation: "преф. новый" },
    { korean: "신고", translation: "заявление, декларация" },
    { korean: "신다", translation: "надевать (на ноги)" },
    { korean: "신문", translation: "газета" },
    { korean: "신발", translation: "обувь" },
    { korean: "신청", translation: "заявление, заявка" },
    { korean: "신호", translation: "сигнал" },
    { korean: "실", translation: "суф комната, помещение" },
    { korean: "실력", translation: "возможности, способности" },
    { korean: "실망", translation: "отчаяние" },
    { korean: "실수", translation: "ошибка, оплошность" },
    { korean: "실업자", translation: "безработный" },
    { korean: "실천", translation: "действительность" },
    { korean: "실현", translation: "реализация, осуществление" },
    { korean: "심다", translation: "сажать, сеять" },
    { korean: "심술궂다", translation: "зловредный" },
    { korean: "심지어", translation: "даже" },
    { korean: "심하다", translation: "глубокий; сильный; резкий" },
    { korean: "심심하다", translation: "скучный" },
    { korean: "싱싱하다", translation: "свежий, живой" },
    { korean: "사우나", translation: "сауна" },
    { korean: "싸우다", translation: "бороться, сражаться; спорить, драться" },
    { korean: "쌀쌀하다", translation: "холодный" },
    { korean: "쌓다", translation: "копить, накапливать" },
    { korean: "썩다", translation: "гнить, портиться" },
    { korean: "썰다", translation: "мелко резать, нарезать" },
    { korean: "쏟다", translation: "выливать, высыпать" },
    { korean: "쏟아지다", translation: "лить (о дожде)" },
    { korean: "쏠리다", translation: "устремляться, увлекаться" },
    { korean: "쓰다", translation: "1) писать 2) надевать (шапку, очки) 3) использовать, расходовать 4) горький" },
    { korean: "쓰레기", translation: "мусор" },
    { korean: "쓰이다", translation: "ф страд залога от 쓰다" },
    { korean: "씌다", translation: "см. 쓰이다" },
    { korean: "씌우다", translation: "ф побуд залога от 쓰다" },
    { korean: "쌍쌍하다", translation: "бодрый, энергичный" },
    { korean: "씻다", translation: "мыть, стирать" },
    { korean: "아가씨", translation: "девушка" },
    { korean: "아기", translation: "малышка, малыш" },
    { korean: "아까", translation: "недавно, только что" },
    { korean: "아내", translation: "жена" },
    { korean: "아니", translation: "не, нет" },
    { korean: "아니다", translation: "не, нет" },
    { korean: "아득하다", translation: "дальний, далекий; давний; туманный" },
    { korean: "아들", translation: "сын" },
    { korean: "아래", translation: "нижняя часть, низ" },
    { korean: "아랫사람", translation: "младший; нижестоящий" },
    { korean: "아름답다", translation: "красивый, прекрасный" },
    { korean: "아마", translation: "вероятно, может быть" },
    { korean: "아무", translation: "кто-то; никто" },
    { korean: "아무리", translation: "как бы ни, сколько бы ни" },
    { korean: "아버님", translation: "вежд отец" },
    { korean: "아버지", translation: "отец" },
    { korean: "아예", translation: "ни в коем случае" },
    { korean: "약", translation: "1) лекарство 2) примерно" },
    { korean: "약간", translation: "немного, несколько" },
    { korean: "약속", translation: "обещание" },
    { korean: "얇다", translation: "тонкий" },
    { korean: "양", translation: "количество" },
    { korean: "양보", translation: "уступка" },
    { korean: "양복", translation: "европейская одежда, костюм" },
    { korean: "양심", translation: "совесть" },
    { korean: "얕다", translation: "мелкий, неглубокий" },
    { korean: "어", translation: "сокр. от 어머니" },
    { korean: "어긋나다", translation: "не совпадать, противоречить, идти вразрез" },
    { korean: "어기다", translation: "нарушать" },
    { korean: "어느", translation: "какой, который" },
    { korean: "어둠", translation: "темнота" },
    { korean: "어둡다", translation: "темный" },
    { korean: "어디", translation: "где, куда" },
    { korean: "어떤", translation: "какой; какой-то" },
    { korean: "어떻게", translation: "как; каким образом" },
    { korean: "어렵다", translation: "трудный, тяжелый" },
    { korean: "어른", translation: "взрослый" },
    { korean: "어리다", translation: "1) молодой, маленький; 2) стоять перед глазами" },
    { korean: "어머니", translation: "мать" },
    { korean: "어부", translation: "рыбак" },
    { korean: "어서", translation: "1) скорее, быстро 2) пожалуйста" },
    { korean: "어울리다", translation: "сливаться в одно целое, гармонировать" },
    { korean: "어제", translation: "вчера" },
    { korean: "어지럽다", translation: "грязный" },
    { korean: "어질다", translation: "добрый и мудрый" },
    { korean: "어째서", translation: "почему" },
    { korean: "어쩔 수 없다", translation: "поневоле, вынужденно" },
    { korean: "우수하다", translation: "превосходный, лучший; совершенный" },
    { korean: "우시장", translation: "скотный рынок" },
    { korean: "우연하다", translation: "случайный" },
    { korean: "우주", translation: "космос" },
    { korean: "우체국", translation: "почта" },
    { korean: "우체통", translation: "почтовый ящик" },
    { korean: "우표", translation: "почтовая марка" },
    { korean: "운동", translation: "движение" },
    { korean: "운영하다", translation: "управлять (предприятием)" },
    { korean: "운전", translation: "вождение, управление" },
    { korean: "울다", translation: "плакать" },
    { korean: "울리다", translation: "звучать, раздаваться" },
    { korean: "울먹이다", translation: "громко плакать, рыдать" },
    { korean: "울음", translation: "плач" },
    { korean: "웃다", translation: "смеяться; улыбаться" },
    { korean: "웃어른", translation: "старший" },
    { korean: "웃음", translation: "смех" },
    { korean: "원수", translation: "недруг, враг" },
    { korean: "원자재", translation: "сырьё" },
    { korean: "월요일", translation: "понедельник" },
    { korean: "웬", translation: "какой, какой-то" },
    { korean: "위", translation: "1) желудок; 2) на, над" },
    { korean: "위성", translation: "спутник" },
    { korean: "위치", translation: "расположение, позиция" },
    { korean: "위하다", translation: "служить (кому-либо), заботиться; любить" },
    { korean: "위협", translation: "угроза" },
    { korean: "유감스럽다", translation: "достойный сожаления" },
    { korean: "유교", translation: "конфуцианство" },
    { korean: "유명하다", translation: "известный, знаменитый" },
    { korean: "유물", translation: "наследие, реликвии" },
    { korean: "유산", translation: "наследие, наследство" },
    { korean: "유용하다", translation: "полезный, пригодный; применимый" },
    { korean: "유익하다", translation: "выгодный, полезный" },
    { korean: "유치원", translation: "детский сад" },
    { korean: "유학", translation: "обучение (учеба) за границей" },
    { korean: "은사", translation: "вежд учитель" },
    { korean: "은빛", translation: "серебристый цвет" },
    { korean: "은행", translation: "банк" },
    { korean: "은해", translation: "доброе дело; благодеяние" },
    { korean: "읊다", translation: "декламировать, читать" },
    { korean: "음료수", translation: "напиток" },
    { korean: "음식", translation: "еда, пища" },
    { korean: "음악", translation: "музыка" },
    { korean: "의견", translation: "точка зрения, мнение" },
    { korean: "의리", translation: "чувство (сознание) долга; долг; справедливость" },
    { korean: "의무", translation: "долг, обязанность" },
    { korean: "의문", translation: "вопрос" },
    { korean: "의미", translation: "значение, смысл" },
    { korean: "의사", translation: "врач, доктор" },
    { korean: "의의", translation: "значение" },
    { korean: "의지", translation: "воля, стремление" },
    { korean: "이", translation: "1) этот; 2) зуб" },
    { korean: "이것", translation: "это; он, она, оно" },
    { korean: "이기다", translation: "победить, одержать победу" },
    { korean: "이까짓", translation: "такой незначительный (пустяковый)" },
    { korean: "이듬해", translation: "следующий год" },
    { korean: "이러하다", translation: "такой, подобный" },
    { korean: "이루다", translation: "создавать, образовывать" },
    { korean: "이룩하다", translation: "осуществлять; достигать, добиваться" },
    { korean: "이름", translation: "имя" },
    { korean: "이리", translation: "1) сюда 2) таким образом" },
    { korean: "이렇다", translation: "делать так" },
    { korean: "이만", translation: "до такой степени; на этом" },
    { korean: "이미", translation: "уже" },
    { korean: "이바지하다", translation: "делать вклад" },
    { korean: "이발소", translation: "парикмахерская" },
    { korean: "이별", translation: "разлука, расставание" },
    { korean: "이사", translation: "переселение, переезд" },
    { korean: "이상하다", translation: "странный, необычный" },
    { korean: "이야기", translation: "рассказ" },
    { korean: "이용하다", translation: "использовать" },
    { korean: "이웃", translation: "сосед" },
    { korean: "이유", translation: "причина" },
    { korean: "이제", translation: "сейчас, теперь" },
    { korean: "이탈리아", translation: "Италия" },
    { korean: "이틀", translation: "второе число; два дня" },
    { korean: "이해", translation: "понимание" },
    { korean: "이행", translation: "выполнение, осуществление" },
    { korean: "인", translation: "1) суф человек; 2) добродетель" },
    { korean: "인격자", translation: "достойный (положительный) человек" },
    { korean: "인구", translation: "население" },
    { korean: "인사", translation: "приветствие" },
    { korean: "인삼", translation: "женьшень" },
    { korean: "인상", translation: "повышение (цены)" },
    { korean: "인생", translation: "(человеческая) жизнь" },
    { korean: "인식", translation: "понимание, осознание" },
    { korean: "인형", translation: "кукла, марионетка" },
    { korean: "인자하다", translation: "гуманный, милосердный" },
    { korean: "인척", translation: "родственник, свойственник" },
    { korean: "일", translation: "дело, работа, занятие" },
    { korean: "일기", translation: "погода" },
    { korean: "일면", translation: "одна сторона" },
    { korean: "일본", translation: "Япония" },
    { korean: "일생", translation: "вся жизнь" },
    { korean: "일어나다", translation: "1) появляться, возникать 2) вставать" },
    { korean: "일요일", translation: "воскресенье" },
    { korean: "일우다", translation: "образовывать" },
    { korean: "일으키다", translation: "поднимать; вызывать; возбуждать" },
    { korean: "일제", translation: "японский империализм" },
    { korean: "일주일", translation: "одна неделя" },
    { korean: "일찍", translation: "1) рано 2) раньше, давно" },
    { korean: "일평생", translation: "см 일생" },
    { korean: "일행", translation: "сопровождающие лица" },
    { korean: "읽다", translation: "читать" },
    { korean: "잃다", translation: "терять, лишаться (чего-л.)" },
    { korean: "입다", translation: "надевать, одеваться" },
    { korean: "입원", translation: "госпитализация" },
    { korean: "잇다", translation: "соединять, связывать" },
    { korean: "있다", translation: "быть, находиться" },
    { korean: "잊다", translation: "забывать" },
    { korean: "자", translation: "ну!" },
    { korean: "자기", translation: "сам; свой" },
    { korean: "자꾸", translation: "всё время, то и дело" },
    { korean: "자네", translation: "ты, твой" },
    { korean: "자다", translation: "спать; ночевать" },
    { korean: "자동차", translation: "автомобиль" },
    { korean: "자라다", translation: "расти" },
    { korean: "자랑하다", translation: "гордиться" },
    { korean: "자르다", translation: "разрезать, распиливать" },
    { korean: "자리", translation: "место" },
    { korean: "자명종", translation: "будильник" },
    { korean: "자식", translation: "сын и дочь; дети" },
    { korean: "자신", translation: "1) сам; себя 2) вера в себя" },
    { korean: "자연", translation: "природа" },
    { korean: "자원", translation: "ресурсы" },
    { korean: "어휘", translation: "лексика" },
    { korean: "언니", translation: "старшая сестра (для женщин)" },
    { korean: "언어", translation: "язык, речь" },
    { korean: "언제", translation: "когда" },
    { korean: "언제나", translation: "всегда, в любое время" },
    { korean: "언젠가", translation: "когда-то; когда-нибудь" },
    { korean: "얻다", translation: "получать, приобретать; доставлять; добиваться" },
    { korean: "얼굴", translation: "лицо" },
    { korean: "얼다", translation: "мерзнуть, замерзать" },
    { korean: "얼마", translation: "сколько 2) немного" },
    { korean: "얼음", translation: "лед" },
    { korean: "엄격하다", translation: "строгий, серьёзный" },
    { korean: "엄마", translation: "мама, мамочка" },
    { korean: "엄하다", translation: "строгий" },
    { korean: "업다", translation: "носить на спине" },
    { korean: "없다", translation: "не быть, не иметься" },
    { korean: "없이", translation: "без" },
    { korean: "엇가다", translation: "исчезать" },
    { korean: "엎다", translation: "опрокидывать, перевертывать" },
    { korean: "여기", translation: "здесь, тут, в этом месте" },
    { korean: "여느", translation: "обычный, обыденный" },
    { korean: "여닫다", translation: "открывать и закрывать; то открывать, то закрывать" },
    { korean: "여러", translation: "много, несколько" },
    { korean: "여론", translation: "общественное мнение" },
    { korean: "여름", translation: "лето" },
    { korean: "여성", translation: "женский пол; женщина" },
    { korean: "여우", translation: "лиса" },
    { korean: "여의다", translation: "потерять (родителей)" },
    { korean: "여자", translation: "женщина" },
    { korean: "여탕", translation: "женское отделение (в бане)" },
    { korean: "여행", translation: "путешествие, поездка" },
    { korean: "역", translation: "станция, вокзал" },
    { korean: "역사", translation: "история" },
    { korean: "역시", translation: "тоже, также" },
    { korean: "역할", translation: "роль" },
    { korean: "연구", translation: "изучение, исследование" },
    { korean: "연극", translation: "спектакль, представление; драма" },
    { korean: "연기", translation: "отсрочка, продление срока; 2) дым; 3) театр, исполнение" },
    { korean: "연락", translation: "связь, контакт" },
    { korean: "연습", translation: "упражнение, тренировка, репетиция" },
    { korean: "연필", translation: "карандаш" },
    { korean: "연해주", translation: "Приморский край" },
    { korean: "열다", translation: "открывать, отворять" },
    { korean: "열리다", translation: "страд залога от 열다" },
    { korean: "열심히", translation: "усердно, прилежно" },
    { korean: "열중하다", translation: "увлекаться, отдаваться чему-либо" },
    { korean: "염려", translation: "тревога, беспокойство" },
    { korean: "염원", translation: "заветное желание" },
    { korean: "영어", translation: "английский язык" },
    { korean: "영원히", translation: "вечно" },
    { korean: "영화", translation: "кинофильм, кинокартина" },
    { korean: "옆", translation: "боковая сторона, бок; сбоку" },
    { korean: "옆집", translation: "соседний дом" },
    { korean: "에어컨", translation: "кондиционер" },
    { korean: "엔지니어", translation: "инженер" },
    { korean: "엔진", translation: "двигатель" },
    { korean: "엘리베이터", translation: "лифт" },
    { korean: "예", translation: "да" },
    { korean: "예보", translation: "прогноз" },
    { korean: "예빌다", translation: "милый, симпатичный" },
    { korean: "예술", translation: "искусство" },
    { korean: "예절", translation: "правила поведения; этикет" },
    { korean: "옛", translation: "древний, старый" },
    { korean: "옛날", translation: "далекое прошлое, древние времена" },
    { korean: "옛말", translation: "архаизм; старинное слово; сказка" },
    { korean: "오가다", translation: "ходить туда-сюда, слоняться, бродить" },
    { korean: "오늘", translation: "сегодня" },
    { korean: "오다", translation: "прибывать, приходить" },
    { korean: "오래", translation: "долго" },
    { korean: "오랜", translation: "давний, старый, древний" },
    { korean: "오랜만", translation: "после долгой разлуки; наконец-то" },
    { korean: "오르다", translation: "подниматься" },
    { korean: "오른", translation: "правый" },
    { korean: "오빠", translation: "старший брат (для женщин)" },
    { korean: "오순도순", translation: "дружно и мирно" },
    { korean: "오염", translation: "загрязнение" },
    { korean: "오전", translation: "время с утра до полудня" },
    { korean: "오직", translation: "только, лишь" },
    { korean: "오징어", translation: "кальмар; каракатица" },
    { korean: "오후", translation: "после полудня" },
    { korean: "온", translation: "весь, целый" },
    { korean: "온도", translation: "температура" },
    { korean: "온돌", translation: "пол с подогревом" },
    { korean: "온종일", translation: "весь день" },
    { korean: "온탕", translation: "горячая ванна" },
    { korean: "올", translation: "яйцо" },
    { korean: "올곧다", translation: "добрый, мягкий, кроткий" },
    { korean: "올바르다", translation: "правильно" },
    { korean: "올해", translation: "этот год" },
    { korean: "옮기다", translation: "переводить, перемещать, переносить" },
    { korean: "옮다", translation: "переезжать, перебираться" },
    { korean: "옳다", translation: "правильный, верный" },
    { korean: "옷", translation: "одежда, платье" },
    { korean: "옷감", translation: "отрез материи; материал" },
    { korean: "옷걸이", translation: "вешалка (для одежды)" },
    { korean: "옷장", translation: "платяной шкаф" },
    { korean: "옹기", translation: "гончарные изделия" },
    { korean: "완성", translation: "завершать (строительные) работы" },
    { korean: "완벽하다", translation: "совершенный, идеальный, безупречный" },
    { korean: "완전", translation: "целый, полный, законченный; чистый; совершенный" },
    { korean: "완전히", translation: "полностью, совершенно" },
    { korean: "완제품", translation: "готовое изделие, фабрикат" },
    { korean: "왕릉", translation: "королевская гробница" },
    { korean: "왜", translation: "почему" },
    { korean: "외국", translation: "внешний мир" },
    { korean: "외국", translation: "иностранное государство" },
    { korean: "외국어", translation: "иностранный язык" },
    { korean: "외국인", translation: "иностранец" },
    { korean: "외로움", translation: "одиночество" },
    { korean: "외롭다", translation: "одинокий" },
    { korean: "외우다", translation: "заучивать, запоминать" },
    { korean: "외출", translation: "выходить, отлучаться" },
    { korean: "외치다", translation: "кричать" },
    { korean: "외투", translation: "пальто" },
    { korean: "요구", translation: "требование, просьба" },
    { korean: "요금", translation: "плата" },
    { korean: "요리", translation: "кухня; блюда" },
    { korean: "요즘", translation: "недавно, на днях" },
    { korean: "요청", translation: "просьба, требование" },
    { korean: "욕심", translation: "жадность, алчность, корыстолюбие" },
    { korean: "용감하다", translation: "отважный, доблестный" },
    { korean: "용무", translation: "дело, занятие" },
    { korean: "우러르다", translation: "смотреть с уважением, с почтением" },
    { korean: "우레", translation: "гром" },
    { korean: "우리", translation: "1) мы; 2) клетка" },
    { korean: "우물", translation: "колодец; родник" },
    { korean: "우산", translation: "зонт" },
    { korean: "우선", translation: "прежде всего" },
    { korean: "자유", translation: "свобода" },
    { korean: "자재", translation: "материал" },
    { korean: "자전거", translation: "велосипед" },
    { korean: "자주", translation: "часто" },
    { korean: "작다", translation: "маленький" },
    { korean: "작성", translation: "составление" },
    { korean: "작정", translation: "намерение, задумка" },
    { korean: "잔", translation: "рюмка; бокал" },
    { korean: "잔소리", translation: "ворчание, брюзжание" },
    { korean: "잔치", translation: "пир" },
    { korean: "잘", translation: "хорошо" },
    { korean: "잔가", translation: "мелкий" },
    { korean: "잘리다", translation: "быть отрезанным (отсечённым, отрубленным)" },
    { korean: "잠", translation: "сон" },
    { korean: "잠그다", translation: "запирать, закрывать" },
    { korean: "잠기다", translation: "быть закрытым" },
    { korean: "잠시", translation: "недолго, немного" },
    { korean: "잠자코", translation: "молча, безмолвно" },
    { korean: "잡다", translation: "держать; ловить" },
    { korean: "잡수시다", translation: "вежл. кушать" },
    { korean: "잡히다", translation: "быть пойманным" },
    { korean: "잡지", translation: "журнал" },
    { korean: "장", translation: "1) сч. сл. лист бумаги; 2) глава, начальник (учреждения)" },
    { korean: "장관", translation: "министр" },
    { korean: "장군", translation: "генерал" },
    { korean: "장난", translation: "шалость, баловство, проказы" },
    { korean: "장래", translation: "будущее, перспективы" },
    { korean: "장례식", translation: "похороны" },
    { korean: "장마철", translation: "сезон дождей" },
    { korean: "장미", translation: "роза" },
    { korean: "장사", translation: "торговля" },
    { korean: "장소", translation: "место" },
    { korean: "장애", translation: "препятствие, помеха" },
    { korean: "장하다", translation: "молодец" },
    { korean: "장학금", translation: "стипендия" },
    { korean: "재능", translation: "способности, талант" },
    { korean: "재다", translation: "измерять, мерить" },
    { korean: "재미", translation: "интерес" },
    { korean: "재배", translation: "возделывание, выращивание" },
    { korean: "재우다", translation: "укладывать спать" },
    { korean: "재정", translation: "финансы" },
    { korean: "재주", translation: "дарование, талант" },
    { korean: "재촉하다", translation: "требовать; побуждать, подгонять, поторапливать" },
    { korean: "재판", translation: "суд" },
    { korean: "저", translation: "1) то; 2) я (уничиж.)" },
    { korean: "저것", translation: "то; он, она, оно" },
    { korean: "저기", translation: "то место; там" },
    { korean: "저녁", translation: "вечер" },
    { korean: "저축하다", translation: "копить, делать сбережения" },
    { korean: "저희", translation: "мы (уничиж.)" },
    { korean: "적", translation: "противник, неприятель, враг" },
    { korean: "적다", translation: "небольшой, маленький" },
    { korean: "적당하다", translation: "соответствующий, подходящий, [при]годный" },
    { korean: "적어도", translation: "по меньшей мере" },
    { korean: "전", translation: "перед, до; до этого" },
    { korean: "전기", translation: "электричество" },
    { korean: "전나무", translation: "пихта цельнолистная" },
    { korean: "전등", translation: "электрическая лампа" },
    { korean: "전력", translation: "электроэнергия" },
    { korean: "전망대", translation: "видовая площадка" },
    { korean: "전문가", translation: "специалист" },
    { korean: "전보", translation: "телеграмма" },
    { korean: "전세계", translation: "весь мир" },
    { korean: "전쟁", translation: "война" },
    { korean: "전차", translation: "трамвай" },
    { korean: "전하다", translation: "передавать" },
    { korean: "전혀", translation: "перед отриц. совсем, совершенно, полностью" },
    { korean: "전파하다", translation: "распространять" },
    { korean: "전화", translation: "телефон" },
    { korean: "절", translation: "буддийский храм (монастырь)" },
    { korean: "절대적", translation: "абсолютный" },
    { korean: "절약", translation: "экономия" },
    { korean: "젊다", translation: "молодой" },
    { korean: "젊어보이다", translation: "выглядеть молодым" },
    { korean: "젊은이", translation: "молодой человек" },
    { korean: "점", translation: "1) точка; 2) пятно; 3) отметка" },
    { korean: "점수", translation: "отметка, оценка, балл" },
    { korean: "점심", translation: "обед" },
    { korean: "점점", translation: "постепенно, мало-помалу" },
    { korean: "젓가락", translation: "палочки для еды" },
    { korean: "정도", translation: "степень; уровень, мера" },
    { korean: "정류소", translation: "остановка" },
    { korean: "정말", translation: "честное слово; в самом деле" },
    { korean: "정복", translation: "покорение" },
    { korean: "정부", translation: "правительство" },
    { korean: "정상", translation: "вершина" },
    { korean: "정성", translation: "искренность, сердечность" },
    { korean: "정책", translation: "политика" },
    { korean: "정치", translation: "политика" },
    { korean: "정하다", translation: "определять; устанавливать" },
    { korean: "정확하다", translation: "правильный, точный" },
    { korean: "젖", translation: "грудь (женская); молоко" },
    { korean: "젖다", translation: "намокать, становиться влажным" },
    { korean: "제", translation: "я; мой, свой" },
    { korean: "제대로", translation: "как нужно, как следует" },
    { korean: "제도", translation: "строй, режим, система" },
    { korean: "제발", translation: "пожалуйста (при просьбе)" },
    { korean: "제법", translation: "довольно, достаточно" },
    { korean: "제일", translation: "1) первый; 2) самый" },
    { korean: "제철", translation: "производство железа" },
    { korean: "제출", translation: "предъявление, представление, выдвижение" },
    { korean: "제자", translation: "ученик" },
    { korean: "조각하다", translation: "ваять, лепить, вырезать" },
    { korean: "조국", translation: "родина, отечество" },
    { korean: "조금", translation: "немного, мало" },
    { korean: "조명", translation: "освещение" },
    { korean: "조모", translation: "бабушка" },
    { korean: "조사", translation: "расследование" },
    { korean: "조선", translation: "Корея" },
    { korean: "조심하다", translation: "быть осторожным" },
    { korean: "조용하다", translation: "тихий, спокойный" },
    { korean: "조카", translation: "племянник, племянница" },
    { korean: "존경", translation: "уважение" },
    { korean: "졸다", translation: "дремать" },
    { korean: "졸업하다", translation: "оканчивать (школу)" },
    { korean: "좁다", translation: "узкий, тесный" },
    { korean: "종류", translation: "род, вид; сорт, порода" },
    { korean: "종합", translation: "универсальный" },
    { korean: "좋다", translation: "хороший, красивый" },
    { korean: "좇다", translation: "идти по пятам; гнаться, преследовать, догонять" },
    { korean: "좋아하다", translation: "любить, нравиться" },
    { korean: "죄", translation: "преступление, проступок" },
    { korean: "좌상", translation: "статуя, изображающая сидящего человека" },
    { korean: "주", translation: "1) см. 주일 2) штат; область, край" },
    { korean: "주년", translation: "годовщина" },
    { korean: "주목주목", translation: "беспрестанно" },
    { korean: "주말", translation: "конец недели; выходные" },
    { korean: "주머니", translation: "мешок; кошелек; сума" },
    { korean: "주먹", translation: "кулак" },
    { korean: "주무시다", translation: "вежл. спать" },
    { korean: "주소", translation: "адрес, местожительство" },
    { korean: "주의", translation: "внимание" },
    { korean: "주인", translation: "владелец, хозяин" },
    { korean: "주일", translation: "неделя" },
    { korean: "주장하다", translation: "настаивать, требовать; утверждать, отстаивать" },
    { korean: "주재", translation: "пребывание" },
    { korean: "주전자", translation: "чайник, самовар" },
    { korean: "주차", translation: "парковка автомобиля" },
    { korean: "주창", translation: "инициатива" },
    { korean: "죽다", translation: "умирать; погибать" },
    { korean: "죽음", translation: "смерть" },
    { korean: "준비", translation: "подготовка" },
    { korean: "줄", translation: "1) верёвка, шнур 2) сл. имя" },
    { korean: "중", translation: "середина; среди" },
    { korean: "중국", translation: "Китай" },
    { korean: "중매", translation: "сваг, сваха" },
    { korean: "중앙", translation: "середина; центр" },
    { korean: "중요하다", translation: "важный, серьезный" },
    { korean: "중용", translation: "умеренность; золотая середина" },
    { korean: "쥐", translation: "мышь" },
    { korean: "쥐다", translation: "брать (в руку), держать" },
    { korean: "즐겁다", translation: "радостный, веселый" },
    { korean: "즐기다", translation: "любить, увлекаться; наслаждаться, радоваться" },
    { korean: "증가하다", translation: "увеличиваться, расти, возрастать; повышаться" },
    { korean: "지갑", translation: "кошелек" },
    { korean: "지구", translation: "земной шар; Земля" },
    { korean: "지극히", translation: "весьма, крайне" },
    { korean: "지금", translation: "теперь, сейчас" },
    { korean: "지나다", translation: "проходить, миновать" },
    { korean: "지나치다", translation: "быть чрезмерным (излишним); превышать" },
    { korean: "지내다", translation: "проводить время; жить" },
    { korean: "지다", translation: "1) падать, опадать; 2) заходить (о солнце, луне) 3) проигрывать, терпеть поражение" },
    { korean: "지대", translation: "зона, район, пояс" },
    { korean: "지도자", translation: "руководитель; инструктор" },
    { korean: "지리", translation: "география" },
    { korean: "지방", translation: "местность, район, область" },
    { korean: "지식", translation: "знания, образованность" },
    { korean: "지우다", translation: "стирать" },
    { korean: "지원", translation: "поддержка, помощь" },
    { korean: "지적하다", translation: "указывать" },
    { korean: "지정하다", translation: "назначать; определять" },
    { korean: "지키다", translation: "охранять, защищать; сохранять; соблюдать, поддерживать" },
    { korean: "지하", translation: "подземный" },
    { korean: "직업", translation: "занятие, профессия; работа" },
    { korean: "직원", translation: "служащий, сотрудник; личный состав, персонал; коллектив" },
    { korean: "직장", translation: "место работы; работа" },
    { korean: "진", translation: "1-я годовщина со дня рождения" },
    { korean: "진땀", translation: "обильный пот" },
    { korean: "진열하다", translation: "выставлять (на выставке); раскладывать (товары), экспонировать" },
    { korean: "진짜", translation: "подлинный, настоящий" },
    { korean: "진찰", translation: "медицинский осмотр, освидетельствование" },
    { korean: "질", translation: "качество и количество" },
    { korean: "질문", translation: "вопрос" },
    { korean: "질서", translation: "порядок" },
    { korean: "질책", translation: "придание, упрек, выговор" },
    { korean: "짐", translation: "груз, ноша, багаж" },
    { korean: "집", translation: "дом" },
    { korean: "집다", translation: "брать (пальцами, палочками для еды)" },
    { korean: "집중하다", translation: "сосредоточиваться, концентрироваться" },
    { korean: "짓다", translation: "делать, создавать; готовить; строить" },
    { korean: "짖다", translation: "лаять, каркать; трещать" },
    { korean: "짙다", translation: "густой" },
    { korean: "짜다", translation: "1) ткать, вязать; 2) соленый" },
    { korean: "짧다", translation: "короткий" },
    { korean: "짬", translation: "растеряться; не знать, куда деваться (от страха и т.п.)" },
    { korean: "쪽", translation: "сторона, направление" },
    { korean: "쫓기다", translation: "1) быть выгнанным (изгнанным); 2) быть преследуемым" },
    { korean: "쫓다", translation: "выгонять, прогонять" },
    { korean: "쭈그리다", translation: "помяться, сжаться" },
    { korean: "즈음", translation: "сын" },
    { korean: "증", translation: "дух" },
    { korean: "찢다", translation: "рвать, разрывать" },
    { korean: "차다", translation: "быть полным (наполненным)" },
    { korean: "차라리", translation: "лучше [бы]" },
    { korean: "차리다", translation: "готовить; устраивать; наряжать; накрывать" },
    { korean: "차이", translation: "различие, разница" },
    { korean: "차츰", translation: "постепенно, мало-помалу" },
    { korean: "착하다", translation: "добрый" },
    { korean: "찬란하다", translation: "яркий, ослепительный" },
    { korean: "참", translation: "действительно, в самом деле" },
    { korean: "참가하다", translation: "принимать участие" },
    { korean: "참관", translation: "осмотр, посещение" },
    { korean: "참다", translation: "терпеть, переносить" },
    { korean: "참되다", translation: "истинный, настоящий" },
    { korean: "참석", translation: "присутствие, участие" },
    { korean: "창", translation: "см. 창문" },
    { korean: "창고", translation: "склад" },
    { korean: "창문", translation: "окно" },
    { korean: "찾다", translation: "искать, отыскивать" },
    { korean: "찾아가다", translation: "посещать" },
    { korean: "채", translation: "при отриц. еще не, не совсем" },
    { korean: "채다", translation: "понимать, догадываться" },
    { korean: "채우다", translation: "наполнять, заполнять" },
    { korean: "책", translation: "книга" },
    { korean: "책기다", translation: "собирать, упаковывать" },
    { korean: "처녀", translation: "девушка" },
    { korean: "처럼", translation: "словно, будто" },
    { korean: "처음", translation: "начало" },
    { korean: "천", translation: "тысяча" },
    { korean: "천천히", translation: "медленно" },
    { korean: "철", translation: "железо, металл" },
    { korean: "첨가하다", translation: "дополнять, добавлять" },
    { korean: "첫", translation: "первый" },
    { korean: "청", translation: "преф. зеленый; молодой" },
    { korean: "청년", translation: "молодежь" },
    { korean: "청소", translation: "чистка, уборка" },
    { korean: "청혼하다", translation: "делать предложение (при вступлении в брак)" },
    { korean: "체결하다", translation: "заключать (договор)" },
    { korean: "체육", translation: "спорт" },
    { korean: "쳐다보다", translation: "уставиться (на что-л.)" },
    { korean: "초대하다", translation: "приглашать (в гости)" },
    { korean: "초라하다", translation: "1) неказистый, серый 2) неважный, незначительный" },
    { korean: "초록잎", translation: "зеленый лист" },
    { korean: "초인종", translation: "входной звонок" },
    { korean: "초청", translation: "приглашение" },
    { korean: "총", translation: "винтовка, ружье" },
    { korean: "최", translation: "преф. самый, наиб..." },
    { korean: "최고", translation: "самый высокий" },
    { korean: "최근", translation: "1) в последнее время; 2) последний; ближайший" },
    { korean: "추억", translation: "воспоминание" },
    { korean: "추위", translation: "холод; мороз" },
    { korean: "추진하다", translation: "толкать вперед, двигать, форсировать, продвигать" },
    { korean: "축구", translation: "футбол" },
    { korean: "축제", translation: "фестиваль" },
    { korean: "축하", translation: "поздравление" },
    { korean: "출국", translation: "выезд из страны" },
    { korean: "출근", translation: "выход на работу" },
    { korean: "출발", translation: "отправление, отъезд" },
    { korean: "출장", translation: "командировка" },
    { korean: "출판하다", translation: "издавать, выпускать" },
    { korean: "춤", translation: "танец, пляска" },
    { korean: "춥다", translation: "холодный" },
    { korean: "충고", translation: "совет" },
    { korean: "충분히", translation: "достаточно, полно" },
    { korean: "취미", translation: "интерес, хобби" },
    { korean: "취직하다", translation: "поступать на работу" },
    { korean: "취하다", translation: "[о]пьянеть" },
    { korean: "측", translation: "сторона" },
    { korean: "치과", translation: "стоматологическое отделение" },
    { korean: "치다", translation: "бить, стучать; играть" },
    { korean: "친", translation: "преф. родной" },
    { korean: "친구", translation: "друг" },
    { korean: "친절히", translation: "любезно, радушно" },
    { korean: "친척", translation: "родственники, родня" },
    { korean: "침", translation: "слюна, слюни" },
    { korean: "침대", translation: "постель, кровать" },
    { korean: "침략", translation: "агрессия" },
    { korean: "칭찬하다", translation: "хвалить" },
    { korean: "평화", translation: "мир" },
    { korean: "포도주", translation: "виноградное вино" },
    { korean: "포기하다", translation: "отказываться" },
    { korean: "포수", translation: "охотник" },
    { korean: "포장", translation: "1) упаковка; 2) мощение, покрытие (дороги)" },
    { korean: "표시하다", translation: "выражать; выявлять" },
    { korean: "표정", translation: "выражение лица" },
    { korean: "표현하다", translation: "выражать, проявлять" },
    { korean: "푸르다", translation: "зеленый; синий; голубой" },
    { korean: "풍부하다", translation: "обильный" },
    { korean: "풀", translation: "достаточно, вдоволь" },
    { korean: "풀", translation: "трава" },
    { korean: "풀다", translation: "развязывать, распутывать; решать, разгадывать" },
    { korean: "풀리다", translation: "ф. страд залога от 풀다" },
    { korean: "품", translation: "1) товар, предмет 2) грудь" },
    { korean: "풍경", translation: "вид, пейзаж" },
    { korean: "풍부하다", translation: "богатый" },
    { korean: "풍속", translation: "обычаи, нравы" },
    { korean: "풍습", translation: "обычаи, привычки" },
    { korean: "풍자", translation: "сатира" },
    { korean: "프로그램", translation: "программа" },
    { korean: "피곤하다", translation: "прил. уставать" },
    { korean: "피로하다", translation: "усталый, утомлённый" },
    { korean: "피사", translation: "г. Пиза" },
    { korean: "피아노", translation: "пианино" },
    { korean: "피우다", translation: "1) цвести; 2) курить" },
    { korean: "필요하다", translation: "нужный, необходимый" },
    { korean: "하나", translation: "один" },
    { korean: "하늘", translation: "небо, небеса" },
    { korean: "하루", translation: "день и ночь; сутки" },
    { korean: "학교", translation: "школа" },
    { korean: "학기", translation: "учебный семестр" },
    { korean: "학문", translation: "наука" },
    { korean: "학부장", translation: "декан" },
    { korean: "학비", translation: "плата за учебу" },
    { korean: "학생", translation: "школьник" },
    { korean: "학습성적", translation: "школьные оценки" },
    { korean: "학자", translation: "ученый" },
    { korean: "한국", translation: "Корея" },
    { korean: "한글", translation: "корейская письменность" },
    { korean: "한꺼번에", translation: "сразу, за один раз" },
    { korean: "한달", translation: "один месяц" },
    { korean: "한동안", translation: "некоторое время" },
    { korean: "한문", translation: "ханмун" },
    { korean: "한복판", translation: "самый центр" },
    { korean: "한식", translation: "корейская кухня" },
    { korean: "한자", translation: "иероглиф" },
    { korean: "한적하다", translation: "тихий и спокойный" },
    { korean: "한참", translation: "некоторое время" },
    { korean: "할머니", translation: "бабушка" },
    { korean: "할아버지", translation: "дедушка" },
    { korean: "핥다", translation: "лизать, лакать" },
    { korean: "함께", translation: "вместе" },
    { korean: "함박눈", translation: "хлопья снега" },
    { korean: "함부로", translation: "беспорядочно, как попало" },
    { korean: "함정", translation: "яма, ловушка, западня" },
    { korean: "합격하다", translation: "выдержать (экзамен)" },
    { korean: "합치다", translation: "соединять, объединять" },
    { korean: "항구", translation: "порт" },
    { korean: "항상", translation: "всегда" },
    { korean: "해", translation: "солнце; год" },
    { korean: "해결하다", translation: "решать, разрешать" },
    { korean: "해어지다", translation: "износиться" },
    { korean: "해외", translation: "заграница" },
    { korean: "행복", translation: "счастье" },
    { korean: "행사", translation: "событие; мероприятие" },
    { korean: "행위", translation: "действие, поступок" },
    { korean: "향기", translation: "душистый аромат, запах" },
    { korean: "향상하다", translation: "улучшаться; повышаться" },
    { korean: "향수", translation: "1) духи, одеколон; 2) тоска по родине" },
    { korean: "향하다", translation: "быть обращенным (в какую-л. сторону), направляться" },
    { korean: "허리", translation: "талия (у одежды)" },
    { korean: "험하다", translation: "крутой, отвесный" },
    { korean: "헤매다", translation: "бродить, шататься" },
    { korean: "헤어지다", translation: "расставаться" },
    { korean: "현대", translation: "настоящее время" },
    { korean: "현재", translation: "настоящее время, теперь" },
    { korean: "협상", translation: "переговоры" },
    { korean: "형", translation: "старший брат" },
    { korean: "형벌", translation: "наказание, кара" },
    { korean: "형수", translation: "жена старшего брата" },
    { korean: "형제", translation: "братья; братья и сестры" },
    { korean: "호기심", translation: "любопытство" },
    { korean: "호랑이", translation: "тигр" },
    { korean: "호소", translation: "призыв, обращение" },
    { korean: "호수", translation: "озеро" },
    { korean: "호텔", translation: "отель, гостиница" },
    { korean: "혹성", translation: "планета" },
    { korean: "혼나다", translation: "испугаться" },
    { korean: "혼동하다", translation: "смешивать, путать" },
    { korean: "혼란", translation: "беспорядок, хаос, неразбериха, смута" },
    { korean: "혼자", translation: "один, сам" },
    { korean: "홀어머니", translation: "вдова" },
    { korean: "화", translation: "гнев, раздражение" },
    { korean: "화답하다", translation: "отвечать" },
    { korean: "화랑", translation: "хваран" },
    { korean: "화려하다", translation: "роскошный, пышный" },
    { korean: "화학", translation: "химия" },
    { korean: "확인", translation: "подтверждение, удостоверение" },
    { korean: "확장", translation: "расширение" },
    { korean: "환갑", translation: "шестидесятилетие" },
    { korean: "환경", translation: "обстановка, ситуация" },
    { korean: "환영", translation: "приветствие; (радостная) встреча, (радушный) прием" },
    { korean: "환율", translation: "обменный курс" },
    { korean: "환자", translation: "больной" },
    { korean: "활동", translation: "деятельность" },
    { korean: "활짝", translation: "настежь (открыть), широко (открываться)" },
    { korean: "회답", translation: "беседа, переговоры" },
    { korean: "회복", translation: "восстановление" },
    { korean: "회사", translation: "компания, фирма" },
    { korean: "회의", translation: "собрание, заседание" },
    { korean: "효도", translation: "почтительность к родителям" },
    { korean: "후", translation: "после, затем" },
    { korean: "훈련", translation: "тренировка, учение" },
    { korean: "훌륭하다", translation: "превосходный, прекрасный, замечательный" },
    { korean: "흔하다", translation: "забрезжить" },
    { korean: "흔히", translation: "весьма, значительно" },
    { korean: "흔들", translation: "плавно летать, парить" },
    { korean: "휴가", translation: "отпуск, каникулы" },
    { korean: "휴식", translation: "отдых, привал; перерыв" },
    { korean: "휴일", translation: "день отдыха, выходной день" },
    { korean: "휴학", translation: "временно не посещать занятия, академический отпуск" },
    { korean: "흉하다", translation: "отвратительный, отталкивающий, противный" },
    { korean: "흐르다", translation: "течь, протекать" },
    { korean: "흐름", translation: "течение" },
    { korean: "흐리다", translation: "мутный, грязный; пасмурный" },
    { korean: "흠뻑", translation: "насквозь (промокнуть)" },
    { korean: "흩어지다", translation: "рассеиваться, разлетаться" },
    { korean: "흰", translation: "белый" },
    { korean: "희망", translation: "надежда, желание" },
    { korean: "희한하다", translation: "редкий, редкостный; невиданный" },
    { korean: "힘", translation: "сила, энергия" },
    { korean: "힘들다", translation: "трудный" }
];

let currentIndex = 0;

// Функция для получения случайного индекса
function getRandomIndex() {
    return Math.floor(Math.random() * words.length);
}

// Функция для обновления слова
function updateWord() {
    const word = words[currentIndex];
    document.getElementById("korean-word").textContent = word.korean;
    document.getElementById("translation-box").textContent = word.translation;
}

// Функция для перехода к следующему слову (случайно)
function nextWord() {
    currentIndex = getRandomIndex();
    updateWord();
    speakText(words[currentIndex].korean);
}

// Функция для перехода к предыдущему слову (случайно)
function previousWord() {
    currentIndex = getRandomIndex();
    updateWord();
    speakText(words[currentIndex].korean);
}

// Функция для озвучивания текста
function speakText(text) {
    if (text) {
        const utterance = new SpeechSynthesisUtterance(text);
        utterance.lang = 'ko-KR'; // Для корейского языка
        speechSynthesis.speak(utterance);
    }
}

// Функция для воспроизведения аудио
function playAudio() {
    speakText(words[currentIndex].korean);
}

// Инициализация первого слова
updateWord();

