
const words = [
    { korean: "물", translation: "вода" },
    { korean: "음식", translation: "еда" },
    { korean: "학교", translation: "школа" },
    { korean: "친구", translation: "друг" },
    { korean: "가족", translation: "семья" },
    { korean: "시간", translation: "время" },
    { korean: "일", translation: "работа" },
    { korean: "가다", translation: "идти ( от говорящего)" },
    { korean: "오다", translation: "идти" },
    { korean: "걱정하다", translation: "беспокоиться" },
    { korean: "건강하다", translation: "быть здоровым" },
    { korean: "계란", translation: "яйцо" },
    { korean: "계약", translation: "договор, контракт" },
    { korean: "계약서", translation: "текст договора, контракта" },
    { korean: "고기", translation: "мясо, рыба" },
    { korean: "물", translation: "вода" },
    { korean: "물고기", translation: "рыба" },
    { korean: "고맙다", translation: "быть благодарным" },
    { korean: "고양이", translation: "кошка" },
    { korean: "공부하다", translation: "учить (ся)" },
    { korean: "공원", translation: "парк" },
    { korean: "과자", translation: "кондитерское изделие (конфеты, печенье …)" },
    { korean: "괜찮다", translation: "неплохой, сносный, нормальный" },
    { korean: "교수", translation: "профессор" },
    { korean: "국수", translation: "куксу (корейская лапша)" },
    { korean: "그", translation: "(э) тот" },
    { korean: "그분", translation: "вежл. он, она" },
    { korean: "그녀", translation: "она" },
    { korean: "그래", translation: "да; так; хорошо" },
    { korean: "그러나", translation: "но; однако" },
    { korean: "그릇", translation: "посуда; тарелка" },
    { korean: "그리고", translation: "и; при этом; затем" },
    { korean: "그만", translation: "хватит, достаточно" },
    { korean: "기분", translation: "настроение" },
    { korean: "기쁘다", translation: "радостный, веселый" },
    { korean: "기쁨", translation: "радость" },
    { korean: "길", translation: "дорога" },
    { korean: "길다", translation: "длинный" },
    { korean: "김치", translation: "кимчхи" },
    { korean: "꼭", translation: "обязательно" },
    { korean: "끝", translation: "конец" },
    { korean: "끝나다", translation: "заканчиваться" },
    { korean: "끝내다", translation: "заканчивать, завершать" },
    { korean: "음식", translation: "еда" },
    { korean: "학교", translation: "школа" },
    { korean: "친구", translation: "друг" },
    { korean: "가족", translation: "семья" },
    { korean: "시간", translation: "время" },
    { korean: "일", translation: "работа" },
    { korean: "공부", translation: "учеба" },
    { korean: "여행", translation: "путешествие" },
    { korean: "휴가", translation: "отпуск" },
    { korean: "영화", translation: "фильм" },
    { korean: "음악", translation: "музыка" },
    { korean: "책", translation: "книга" },
    { korean: "커피", translation: "кофе" },
    { korean: "차", translation: "чай" },
    { korean: "빵", translation: "хлеб" },
    { korean: "과일", translation: "фрукты" },
    { korean: "야채", translation: "овощи" },
    { korean: "고기", translation: "мясо" },
    { korean: "생선", translation: "рыба" },
    { korean: "계란", translation: "яйцо" },
    { korean: "우유", translation: "молоко" },
    { korean: "치즈", translation: "сыр" },
    { korean: "버터", translation: "масло" },
    { korean: "소금", translation: "соль" },
    { korean: "설탕", translation: "сахар" },
    { korean: "나", translation: "я" },
    { korean: "나쁘다", translation: "плохой" },
    { korean: "나중에", translation: "потом, в конце" },
    { korean: "날", translation: "день" },
    { korean: "날다", translation: "летать" },
    { korean: "날씨", translation: "погода" },
    { korean: "남자", translation: "мужчина" },
    { korean: "남편", translation: "муж" },
    { korean: "낮", translation: "день" },
    { korean: "내일", translation: "завтра" },
    { korean: "너", translation: "ты" },
    { korean: "놀다", translation: "гулять, веселиться" },
    { korean: "놀음", translation: "игра" },
    { korean: "놈", translation: "презрен. человек, тип" },
    { korean: "농담하다", translation: "шутить" },
    { korean: "누구", translation: "кто" },
    { korean: "뉘", translation: "кто" },
    { korean: "늘", translation: "всегда, постоянно" },
    { korean: "늦다", translation: "поздний; опаздывать" },
    { korean: "달", translation: "луна, месяц" },
    { korean: "닭", translation: "курица" },
    { korean: "당신", translation: "Вы" },
    { korean: "대학", translation: "институт" },
    { korean: "대학교", translation: "университет" },
    { korean: "돈", translation: "деньгим" },
    { korean: "뛰다", translation: "прыгать, подпрыгивать; скакать; бежать" },
    { korean: "라디오", translation: "радио" },
    { korean: "러시아", translation: "Россия" },
    { korean: "러시아말", translation: "русский язык" },
    { korean: "러시아사람", translation: "русский (человек)" },
    { korean: "로봇", translation: "робот" },
    { korean: "마다", translation: "каждый" },
    { korean: "만나다", translation: "встречать (ся)" },
    { korean: "만년필", translation: "авторучка" },
    { korean: "만두", translation: "пельмени" },
    { korean: "만들다", translation: "делать, изготавливать" },
    { korean: "마냑", translation: "если; допустим (предположим), что" },
    { korean: "많다", translation: "многочисленный; много" },
    { korean: "말", translation: "конь; слово; язык" },
    { korean: "말을 걸다", translation: "заводить разговор" },
    { korean: "말하다", translation: "говорить, рассказывать" },
    { korean: "매우", translation: "очень" },
    { korean: "매일", translation: "каждый день" },
    { korean: "머리", translation: "голова" },
    { korean: "머리가 나쁘다", translation: "глупый" },
    { korean: "머리가 좋다", translation: "умный" },
    { korean: "모르다", translation: "не знать; не уметь" },
    { korean: "무엇", translation: "что; что – то" },
    { korean: "무엇인가", translation: "что – нибудь" },
    { korean: "미", translation: "красота" },
    { korean: "미국", translation: "Америка" },
    { korean: "미소", translation: "улыбка" },
    { korean: "미소를 짓다", translation: "улыбаться" },
    { korean: "거짓말", translation: " ложь" },
    { korean: "건강", translation: "здоровье " },
    { korean: "급료", translation: "зарплата" },
    { korean: "기억", translation: "память" },
    { korean: "깊다", translation: "глубокий " },
    { korean: "대통령", translation: "президент" },
    { korean: "맥락", translation: "контекст" },
    { korean: "박람회", translation: "ярмарка" },
    { korean: "박물관", translation: "музей" },
    { korean: "속력", translation: "скорость" },
    { korean: "속도", translation: "скорость" },
    { korean: "식당", translation: "ресторан " },
    { korean: "식물", translation: "растение" },
    { korean: "심리학", translation: "психология" },
    { korean: "일본", translation: "Япония" },
    { korean: "읽다", translation: "читать" },
    { korean: "점심", translation: "обед" },
    { korean: "정류장", translation: "остановка" },
    { korean: "진리", translation: "правда" },
    { korean: "칼", translation: "нож" },
    { korean: "학년", translation: "учебный год" },
    { korean: "가을", translation: "осень" },
    { korean: "겨울", translation: "зима" },
    { korean: "교실", translation: "класс" },
    { korean: "금요일", translation: "пятница" },
    { korean: "낮", translation: "день" },
    { korean: "날", translation: "день" },
    { korean: "내일", translation: "завтра" },
    { korean: "년", translation: "год" },
    { korean: "다음", translation: "следующий" },
    { korean: "달", translation: "месяц (корейское слово)" },
    { korean: "월", translation: "месяц (китайское слово)" },
    { korean: "달러", translation: "доллар" },
    { korean: "동안", translation: "в течение" },
    { korean: "마다", translation: "каждый" },
    { korean: "몇", translation: "сколько" },
    { korean: "얼마나", translation: "сколько" },
    { korean: "목요일", translation: "четверг" },
    { korean: "밤", translation: "ночь" },
    { korean: "봄", translation: "весна" },
    { korean: "분", translation: "минута" },
    { korean: "사람", translation: "человек" },
    { korean: "среда", translation: "среда" },
    { korean: "시", translation: "час" },
    { korean: "시간", translation: "час (промежуток времени)" },
    { korean: "아침", translation: "утро" },
    { korean: "어제", translation: "вчера" },
    { korean: "여름", translation: "лето" },
    { korean: "연필", translation: "карандаш" },
    { korean: "오늘", translation: "сегодня" },
    { korean: "오전", translation: "первая половина дня" },
    { korean: "오후", translation: "вторая половина дня" },
    { korean: "요일", translation: "день недели" },
    { korean: "월요일", translation: "понедельник" },
    { korean: "일요일", translation: "воскресенье" },
    { korean: "자정", translation: "полночь" },
    { korean: "저녁", translation: "вечер" },
    { korean: "전화", translation: "телефон" },
    { korean: "지난", translation: "прошлый" },
    { korean: "지난 번에", translation: "прошлый раз" },
    { korean: "초", translation: "секунда" },
    { korean: "토요일", translation: "суббота" },
    { korean: "학생", translation: "ученик, студент" },
    { korean: "화요일", translation: "вторник" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },
    // { korean: "주스", translation: "Сок" },

];

let currentIndex = 0;

// Функция для получения случайного индекса
function getRandomIndex() {
    return Math.floor(Math.random() * words.length);
}

// Функция для обновления слова
function updateWord() {
    const word = words[currentIndex];
    document.getElementById("korean-word").textContent = word.korean;
    document.getElementById("translation-box").textContent = word.translation;
}

// Функция для перехода к следующему слову (случайно)
function nextWord() {
    currentIndex = getRandomIndex();
    updateWord();
    speakText(words[currentIndex].korean);
}

// Функция для перехода к предыдущему слову (случайно)
function previousWord() {
    currentIndex = getRandomIndex();
    updateWord();
    speakText(words[currentIndex].korean);
}

// Функция для озвучивания текста
function speakText(text) {
    if (text) {
        const utterance = new SpeechSynthesisUtterance(text);
        utterance.lang = 'ko-KR'; // Для корейского языка
        speechSynthesis.speak(utterance);
    }
}

// Функция для воспроизведения аудио
function playAudio() {
    speakText(words[currentIndex].korean);
}

// Инициализация первого слова
updateWord();
